### PR TITLE
FileQuery + CORS

### PR DESCRIPTION
**Pull request by imachug**
Hello! I know `fileQuery` is quite an old thing, but it is useful to query some CORS sites that don't have any database.

So this PR adds two options:
1. First, it adds `fileQuery` to `corsFuncWrapper` list, so you can `fileQuery("cors-something...")` now.
2. The second change, which isn't connected with CORS, `fileQuery("file", "posts.slug=home")` is valid now - so you can use a string as value for searching.

### CODE REVIEW

**Comment by imachug** [comment]
@HelloZeroNet Any news?

**Comment by HelloZeroNet** [comment]
The problem is FileQuery will get slow after a certain amount of file, so I not sure if we should encourage using it.

**Comment by imachug** [comment]
I know, but there is no way to query data from ZeroWiki when I add it as CORS.

Kaffiene does use ZeroWiki's database, but it uses JavaScript SQLite.

**Comment by HelloZeroNet** [comment]
Then adding cross-site database query support sounds better for me if it would solve the problem.

**Comment by imachug** [comment]
@HelloZeroNet I can PR that - should it be support for `dbschema.json`:

```
maps: {
    "cors-.*/...": ...
}
```

or should it be a command `corsDbQuery("address", "query", params)`?

**Comment by HelloZeroNet** [comment]
Working on it... I will change the (currently undocumented) "As" command to allow this.
It should not take long :)

**Comment by imachug** [comment]
Thank you!

**Comment by imachug** [comment]
@HelloZeroNet Let me check.

**Comment by imachug** [comment]
Wait - this doesn't work:

```
page.cmd("as", ["138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP", "dbQuery", "SELECT * FROM json WHERE json_id = :param", {param: param}])
```

**Comment by HelloZeroNet** [comment]
Try this way: `page.cmd("as", ["138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP", "dbQuery", ["SELECT * FROM json WHERE json_id = :param", {param: param}]])`

**Comment by imachug** [comment]
Yeah, it works - thank you for implementing this. Though I think that should be documented somewhere.

**Comment by HelloZeroNet** [comment]
Just added it:

https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#as-address-cmd-arguments

**Pull request closed without merging**
