### PR TITLE
Support compressed keys

### LINKED ISSUE #2501: Support for compressed Bitcoin vanity addresses
**Is your feature request related to a problem? Please describe.**

For example, I want to have a vanity address for my site. I use some vanity generator (like VanityGen or VanitySearch) to generate it and get address and private key.

But Bitcoin has two types of classic (`1`) addresses: compressed and uncompressed. And it seems that ZeroNet only supports uncompressed version, which makes it impossible to use it with compressed vanity addresses (it is possible if you convert it to uncompressed version but this doesn't make sense because you would lose vanity prefix).

For example, let's say that I generated some compressed vanity address, for example `1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io` (it's not vanity or used on any site but just example). Its compressed private key is `L3ocupNWioTwhLgu64xcSs5mGSZEPd6LevpUMmiZ2Q8E25Pah1x9`. Based on bitaddress.org, the uncompressed version of this private key is `5KJp75PYf21fg3eb1F3BJBtq6K2QstgGnJBJXXyYGiweqq25stV`, which results in `1K5XQVPpdxAyBnocSp6GhqnfJ77TESQB7d` as uncompressed address.

I can successfully use `1K5XQVPpdxAyBnocSp6GhqnfJ77TESQB7d` (uncompressed address) as address of my site. Signing it with uncompressed private key works normally.

However, given that my vanity address is compressed, I want to to use it for site address. So I create site with "vanity" compressed address `1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io` in the same way as previously. But when I try to sign it, it doesn't work.

When I try to sign it with compressed private key, it results in this signing error:

```
Error signing content.json
Private key invalid! Valid signers: ['1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io'], Private key address: 1CVdzwL9c2WVEkHMmkrHS9o6CD4WQaj2iR
```

When I try it with uncompressed private key, it also results in a similar error:

```
Error signing content.json
Private key invalid! Valid signers: ['1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io'], Private key address: 1K5XQVPpdxAyBnocSp6GhqnfJ77TESQB7d
```

In this case, you can see that it detects private key's address as uncompressed version, but fails to sign it because I want to use it on compressed address.

**Describe the solution you'd like**

ZeroNet should support both compressed and uncompressed Bitcoin addresses.

### PR DESCRIPTION
**Pull request by purplesyringa**
Closes #2501 and #2502. This is a less hacky solution, compressed key handling was moved to sslcrypto.

@filips123 Could you please check if publishing to another machine still works?

### CODE REVIEW

**Comment by purplesyringa** [comment]
A segfault in sqlite, huh.

**Comment by filips123** [comment]
It seems to work. I created two ZeroTalk clones:

* [`1BXjuMLWBG3PovvdyV4r1pgNrecLNatSqH`](http://127.0.0.1:43110/1BXjuMLWBG3PovvdyV4r1pgNrecLNatSqH/) with uncompressed address
* [`1B7N3frmgHsQCztg8U6Q1g7KVk2dS3SA3Z`](http://127.0.0.1:43110/1B7N3frmgHsQCztg8U6Q1g7KVk2dS3SA3Z/) with compressed address

I was able to sign and publish both of them, and both also work on another ZeroNet instance without these changes. And publishing users' content also work without changes.

**Comment by purplesyringa** [comment]
Great, waiting for @HelloZeroNet to merge the PR then.

**Comment by HelloZeroNet** [comment]
Thanks!

**Comment by ghost** [comment]
@HelloZeroNet @imachug @filips123 

Makes no sense to publish the same site under two different Bitcoin address, while you can have different content on them I still don't get it why this was necessary. Signing the exact same content with the same private key on both the uncompressed and compressed address will **allows me to recover your private key instantly**!

**Comment by purplesyringa** [comment]
> allows me to recover your private key instantly

I'm really interested in seeing how it's possible.

**Comment by filips123** [comment]
> Makes no sense to publish the same site under two different Bitcoin address

Who said that you need to publish site on both addresses. You can just use compressed address and publish site to it and leave uncompressed one.

> allows me to recover your private key instantly

Ok. I have site [ZeroTalk Compressed Address](http://127.0.0.1:43110/1B7N3frmgHsQCztg8U6Q1g7KVk2dS3SA3Z/) and [ZeroTalk Uncompressed Address](http://127.0.0.1:43110/1BXjuMLWBG3PovvdyV4r1pgNrecLNatSqH/). Both are signed with the same private key, one with compressed public key and one with uncompressed. Now, where is my private key?

Also, to make things a bit "easier," here is the same message signed with compressed and uncompressed address of the same private key:

```
-----BEGIN BITCOIN SIGNED MESSAGE-----
Hello World
-----BEGIN SIGNATURE-----
1B7N3frmgHsQCztg8U6Q1g7KVk2dS3SA3Z
IHktsPPjwy5B7jlvQBA8nX+jjUB6Z0owpGTGtptwAyaUnHkEz1eOq78PWhWgV1lAINezo/sC/EeqlZyyKUOQR30=
-----END BITCOIN SIGNED MESSAGE-----
```

```
-----BEGIN BITCOIN SIGNED MESSAGE-----
Hello World
-----BEGIN SIGNATURE-----
1BXjuMLWBG3PovvdyV4r1pgNrecLNatSqH
HJz85ZdaDlL+vDdaOvu+Ng/D9/CDhVwXt7fnp0xchBGieixY/eOUTV/PrTwDIgFAwApjbJcHk0OUzEBubVjyEkU=
-----END BITCOIN SIGNED MESSAGE-----
```

**Comment by ghost** [comment]
Send some Bitcoin to the un(compressed) address and spend it. 1 satoshi for example. I need some values for SAGE. signers_sign in content.json I get it (signature) but "signs" is not really clear for me at this point. Are you signing the Bitcoin address or that is the message?

**Comment by ghost** [comment]
All in all, it is incredibly stupid to have this vulnerability in ZeroNet. If someone ever uses the Bitcoin address used to publish on ZeroNet to receive funds, and move those funds, than actually the signatures from content.json and some values from the Bitcoin transaction will allow the recovery of the private key. Yes, instantly.

**Comment by filips123** [comment]
So explain how does it work? And if it is such serious vulnerability, won't be good to (securely) report it to Bitcoin developers?

**Comment by filips123** [comment]
> Send some Bitcoin to the un(compressed) address and spend it. 1 satoshi for example.

I don't have plans for spending any money for this, but if you send me some Bitcoins, I can try 😀

> Are you signing the Bitcoin address or that is the message?

If you think about these two messages:

* I'm signing message `Hello World`
* With the same private key private key as compressed (`1B7N3frmgHsQCztg8U6Q1g7KVk2dS3SA3Z`) and uncompressed (`1BXjuMLWBG3PovvdyV4r1pgNrecLNatSqH`) address (separatly)
* Which produces `IHktsPPjwy5B7jlvQBA8nX+jjUB6Z0owpGTGtptwAyaUnHkEz1eOq78PWhWgV1lAINezo/sC/EeqlZyyKUOQR30=` (compressed) and `HJz85ZdaDlL+vDdaOvu+Ng/D9/CDhVwXt7fnp0xchBGieixY/eOUTV/PrTwDIgFAwApjbJcHk0OUzEBubVjyEkU=` (uncompressed) signatures.

**Comment by ghost** [comment]
Take a look at this: https://crypto.stackexchange.com/a/57851 and this: https://eprint.iacr.org/2013/346 

@filips123 the more you sign with that private key (both) your (un)compressed address, the more likely that the private key recovery will be successful. Still I would need to see some transactions from those addresses. 

ZeroNet should avoid allowing users to use both compressed and uncompressed addresses for the exact same content (signing using the exact same private key). It would be however good idea to have uncompressed address for addressing sites and compressed to receive funds. 

I can't see any useful case allowing both. Just like @filips123 he also published the exact same content on both address, which makes no sense and dangerous.

**Comment by filips123** [comment]
> Take a look at this: crypto.stackexchange.com/a/57851 and this: eprint.iacr.org/2013/346

But where do this mention compressed and uncompressed addresses? The first website just mentions using the same `k` for signing different messages with the same private key. And the second mentions "power analysis attack" which I'm pretty sure you won't be able to do it using ZeroNet.

**Comment by ghost** [comment]
@imachug can you do something about this: "entropy=None"?
Not only here: https://github.com/HelloZeroNet/ZeroNet/commit/fa880d99f14c7d2c970cec694378a89522f3d1eb#diff-393bd9cc319dd55c51b3068a7ae59e9bR461

for those who don't know what is entropy ([source](https://protocoin.readthedocs.io/en/v0.2/modules.html)): 

> **entropy** – A function that accepts a parameter with the number of bytes and returns the same amount of bytes of random data, use a good source of entropy. When this parameter is ommited, the OS entropy source is used.

**Comment by ghost** [comment]
@imachug @filips123 https://github.com/warner/python-ecdsa#entropy and more importantly **Deterministic Signatures**: https://github.com/warner/python-ecdsa#deterministic-signatures :thinking: 

@HelloZeroNet can you see what I see in @imachug's sslcrypto?

**Comment by purplesyringa** [comment]
Okay... If you read a little bit below, the `if not entropy:` part does *exactly* what that RFC specifies.

**Pull request merged**
