### PR TITLE
Add tray icon again when explorer restarted

### PR DESCRIPTION
**Pull request by ysc3839**
Also add zeronet.conf to .gitignore.

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Can't test it, but looking good. Thanks

**Comment by ysc3839** [comment]
Run ZeroNet and you can see the tray icon, then kill explorer.exe and start it again, the icon disappear.

**Comment by HelloZeroNet** [comment]
there is no explorer.exe on win10

**Comment by ysc3839** [comment]
What? Can you take a screenshot?

**Comment by HelloZeroNet** [comment]
Yeah you are right, there is explorer.exe, but after kill/restart it i got:
```
[11:38:21] - Unhandled exception
Traceback (most recent call last):
  File "plugins\Trayicon\lib\notificationicon.py", line 558, in _run
    TranslateMessage(ctypes.pointer(message))
ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected LP_MSG instance instead of LP_MSG
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "plugins\Trayicon\lib\notificationicon.py", line 646, in _callback
    Shell_NotifyIcon(NIM_ADD, ctypes.pointer(self.iconinfo))
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_NOTIFYICONDATA instance instead of LP_NOTIFYICONDATA
```

**Comment by ysc3839** [comment]
It seems OK in my computer.
snipaste20161112_192701

**Comment by HelloZeroNet** [comment]
Yeah, the error message makes no sense and if I run notificationicon.py standalone, then it comes back correctly

**Pull request merged**
