### PR TITLE
Update requirements.txt (again)

### PR DESCRIPTION
**Pull request by ghost**
@HelloZeroNet gevent>=1.5.0; python_version >= "3.5" is not needed but I let it for now (change it in a few minutes), gevent>=1.4.0 (and ONLY this) is way enough to be in requirements.txt!!! Ask @filips123, if you are so f**ng ignorant that just searching for excuses to close my PR.  
@imachug can you talk with Tamas? :/

### CODE REVIEW

**Comment by ghost** [comment]
@filips123 said correctly here: https://github.com/HelloZeroNet/ZeroNet/pull/2518#issuecomment-612412146
> > Since Gevent 1.5.0 supports all version from 2.7.9 to up, except 3.4
> 
> **It support Python 2.7+, except 3.0, 3.1, 3.2 and 3.3. Basically Python 2.7 and 3.5+.**

So why you write in requirements.txt **gevent>=1.5.0; python_version >= "3.8"**??? You don't even read the PR dude... :-1:

**Comment by ghost** [comment]
@imachug @filips123 @HelloZeroNet this is from Travis (https://travis-ci.org/github/HelloZeroNet/ZeroNet/jobs/674132588) log: 

$ python --version
Python 3.8.0

$ pip --version
pip 19.3 from /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/pip (python 3.8)

$ pip install --upgrade -r requirements.txt
Collecting gevent>=1.4.0
 Using cached **gevent-1.5.0-cp38-cp38-manylinux2010_x86_64.whl** (5.9 MB)

**Comment by purplesyringa** [comment]
I've just thought about something... ZeroNet is now PyPy-compatible but the fix requires gevent 1.5.0. Perhaps we should set `gevent>=1.5.0` for Python 3.5+ and `gevent>=1.4.0` for Python 3.4.

**Comment by ghost** [comment]
@imachug @filips123 

$ python --version
**Python 3.8.2**
$ python3 -m venv test
$ source test/bin/activate

(test) zero@net:~/opt/zeronet# pip3 install **--no-cache-dir** -r requirements.txt
Collecting gevent>=1.4.0
  Downloading gevent-1.5.0-cp38-cp38-manylinux2010_x86_64.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB 708 kB/s 
Collecting msgpack>=0.4.4
  Downloading msgpack-1.0.0-cp38-cp38-manylinux1_x86_64.whl (303 kB)
     |████████████████████████████████| 303 kB 746 kB/s 

As you see, pip now is not looking for the cached version and is clearly downloading **gevent-1.5.0** in venv.

**Comment by purplesyringa** [comment]
> As you see, pip now is not looking for the cached version and is clearly downloading gevent-1.5.0 in venv.

The problem is when gevent-1.4.0 is already cached (e.g. gevent was installed when 1.5.0 wasn't available yet).

**Comment by ghost** [comment]
@imachug as I said to you: https://github.com/HelloZeroNet/ZeroNet/pull/2523#issuecomment-612672156

Nobody installed gevent 1.4.0 before! You know why? Because, **requirements.txt had a version of 1.1.0 in ZeroNet for years!** If someone has lower version than 1.4.0, requirements.txt will upgrade it!

**Comment by HelloZeroNet** [comment]
1.4.0 is not compatible with Python 3.8, so it won't work for people who already have 1.4.0 installed.

**Pull request closed without merging**
