### PR TITLE
Fix shebang

### PR DESCRIPTION
**Pull request by Nephos**
python2 instead of python

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
It does not work on osx. according to http://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take `#!/usr/bin/env python` always should point to python2

**Comment by Nephos** [comment]
> #!/usr/bin/env python always should point to python2

No it doesn't. This is why it doesn't work on my linux.

>  $>  /usr/bin/env python --version
> 
> Python 3.5.1


Furthermore, I will quote your source :+1: 

> ... python should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3.

So please **fix** the shebang because it is not.

**Comment by Nephos** [comment]
see: http://127.0.0.1:43110/1MyPktAWvYQQiLBNuApBZKUL2xNqQmAE6D/?Post:6

**Comment by HelloZeroNet** [comment]
```
$ /usr/bin/env python2
/usr/bin/env: python2: No such file or directory
```
for me

**Comment by Nephos** [comment]
I moved my old master branch to patch-shebang, i will reopen a new merge request later.

There is an issue on OSX (no python2 executable).

As OSX has not the standard python2 executable, OSX users should install a virtual env.

see: http://stackoverflow.com/questions/3713097/upgrading-python-in-virtual-env

**Comment by HelloZeroNet** [comment]
please correct your PR then i will accept the modification

**Comment by Nephos** [comment]
Tested on OSX. It seems that OSX has

- python
- python2.7
- python3.3
- python3

but not python2.

Waiting for you reply.

**Comment by Nephos** [comment]
rebased

**Pull request merged**
