### PR TITLE
Added optional redirect value for siteClone

### PR DESCRIPTION
**Pull request by rllola**
Added an argument which allow the developer to not redirect to the newly cloned site.

See #1891;

### CODE REVIEW

**Comment by imachug** [comment]
This is not enough. In case the redirect does *not* happen, we should also return the cloned site address -- otherwise, there's no way to get it.

**Comment by rllola** [comment]
Yeah good point. I am on adding this.

**Comment by rllola** [comment]
It now returns the address of the newly cloned site.

@HelloZeroNet ready for review.

**Comment by HelloZeroNet** [comment]
Thanks, looking great!

**Comment by imachug** [comment]
Cool, thanks for merging.

**Pull request merged**
