### PR TITLE
Update hu.json

### PR DESCRIPTION
**Pull request by GiganticBlackBear**
~~prviát~~ to privát

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks

**Comment by TheBlackBearEatsYou** [comment]
@filips123 @imachug do you like my contribution? :rofl: :hugs:

**Comment by TheBlackBearEatsYou** [comment]
> Thanks

Semmiseg Tomi. :hugs:

**Comment by imachug** [comment]
Hey @HelloZeroNet we're kinda legally fucked up unless you can prove this change can't be copyrighted... I guess it'd be easy to do though.

**Pull request merged**
