### PR TITLE
Upgraded the license and creating files for the repository.

### PR DESCRIPTION
**Pull request by ghost**
@imachug @filips123 please see this. This is how ZeroNet complies with licenses! I created some additional files also because they are required.

### CODE REVIEW

**Comment by filips123** [comment]
Why do we need 10 more files just for license change? All of those things are already described either in README or GitHub itself. The only file changes needed would be LICENSE (with new license text) and README (with short license notice).

In README, there is already an installation and usage section and documentation. Short license notice (LICENSE file in your changes) should also be just added to section of README.

Change log and contributors are also displayed on GitHub website (change log is in GitHub Releases, contributors are also displayed automatically on list), so additional files are useless.

Yes, this is how FSF recommends things, but these recommendations were created a long time before GitHub had all these features and now they (recommendations) are basically useless. Multiple license-related files will also confuse GitHub to show "view license file"/"unknown license" instead of correct license and most modern open-source projects just use single LICENSE file with short notice in README.

**Comment by ghost** [comment]
@filips123 
**I don't give a damn about GitHub!**
> Why do we need 10 more files just for license change?

Each file has a very specific purpose:

`COPYING` = license terms (**text/x-copying**)
`INSTALL` = installation instructions (**text/x-install**)
`ChangeLog` = document (**text/x-changelog**)



You can't use the single `LICENSE` file because that would mean GPLv3-only! 
The GPLv3+ `LICENSE` must be represented this way. 

The `LICENSE` file will be detected by scanners as **GPLv3+** and the `COPYING` file is includes the full text of the GPLv3.

**Comment by filips123** [comment]
> I don't give a damn about GitHub!

And? Then I don't give a damn about your unnecessary files.

> Each file has a very specific purpose

Each of this purposes is already supported directly on GitHub website.

**Comment by ghost** [comment]
Than go and fuck yourself! This files stay in my repository this way and you must upgrade the license in yours because ZeroNet is distributed illegally in this very moment!

**Comment by filips123** [comment]
Explain why are these files needed if GitHub shows the same information on their website.

Also, if I say "The project is licensed under GPLv3+" in README and include GPLv3 text in LICENSE, why won't this be OK? From GitHub documentation:

> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

**Comment by purplesyringa** [comment]
Sure, let them stay this way in your repository. But please don't affect ours.

**Comment by ghost** [comment]
> Explain why are these files needed if GitHub shows the same information on their website?

@filips123 
I did explained very respectfully. I'm not going to argue. 

@imachug
This repository must comply with the terms of the license! In the other hand, I'm a contributor of ZeroNet so is **our** repository, like it or not!

The voting https://github.com/HelloZeroNet/ZeroNet/issues/2273 can be also closed by now.

**Comment by filips123** [comment]
> I did explained very respectfully. I'm not going to argue.

No, you didn't. You only explain what that files would be used for. You didn't explain why do you need that files if data are already on GitHub.

> This repository must comply with the terms of the license!

Where is it stated that repository must have that files and that GitHub's data are not enough?

> The voting #2273 can be also closed by now.

The PR #2296 can be also closed by now.

**Comment by ghost** [comment]
I claim all rights over my contribution right in this moment so you must reverse all the merges. I will not contribute to any repository which distributes software illegally and not giving credit for my contribution.

**Comment by filips123** [comment]
So you own the copyright for detecting and handling MIME types? Why then don't you sue Apache or other web servers which use the same way of handling MIME types?

Or even better, where is your proof that you didn't steal that code from Apache or another web server?

**Comment by ghost** [comment]
Yes, I own the copyright! Without me you would not merged that into the software and clearly for years none of you did!

**Comment by filips123** [comment]
Again, please answer what I asked you. Is [this diffreance](https://github.com/HelloZeroNet/ZeroNet/pull/2248#issuecomment-549682814) not enough for you?

**Comment by ghost** [comment]
I don't need to prove anything! However, every single contributor must **immediately stop distributing the ZeroNet software illegally**!

**Comment by filips123** [comment]
Nobody need to stop distributing the ZeroNet software. However, you must prove **what I asked you for**!

**Comment by purplesyringa** [comment]
Words don't count as contribution, code does! Go RTFM.

**Comment by ghost** [comment]
I don't care what you count or not! It is my contribution! Without me this changes never even would be made! So reversing the file! Find other ways to fix your issues! Not using my pull requests without giving me credit! I going to sue if in any way the file is similar to to my pull request!

**Comment by filips123** [comment]
> No credit is given to me for this contribution, figure out other way to fix your problems or keep it how you used it for years. I reserve all right to my contribution.
>
> I going to sue if in any way the file is similar to to my pull request!

Oh yes. So you own the copyright for handling MIME types according to RFC and IANA?

**Comment by ghost** [comment]
The point is you did not fixed this for more than 4 years, when I come and sent a pull request my contribution is discredited and merged in someone elses name! I will not going to allow this! 

You had many years to fix this issue and you did not so don't you come here now and cry to me about that I removing my contribution!

This pull request is archived: 

- https://web.archive.org/web/20191109193240/https://github.com/HelloZeroNet/ZeroNet/pull/2296
- https://web.archive.org/web/20191109193357/https://github.com/HelloZeroNet/ZeroNet/pull/2296/commits/db0ee308bda8b904b9f13725e30d5c9447d83421

**Comment by purplesyringa** [comment]
Telling people about problems is **not** a contribution from legal side.

**Comment by ghost** [comment]
I did sent code! Lastly ZeroNet is the one which violates other people copyrights and licenses also for years! Don't you even try to discredit my pull request! I going to sue the hell out of this repository and its owners if the licensing issue is not resolved urgently! Remove my contribution from ZeroNet and don't you even try to implement similar code what is sent in the pull request!

**Not enough that ZeroNet violated more than 3 licenses and copyright of many other people for years?** Now you try to stole my contribution too? I sue ZeroNet maintainers for both the license and the discredit of my contribution if this is the case!

**Comment by filips123** [comment]
Yes, we see that GitHub legal stuff is on your side as they removed at least 10 of your accounts. Of course totally not because of violating their ToS.

**Comment by ghost** [comment]
They removed all those accounts because you and other criminals reported them in order to try to cover up the fact that you are a worthless license abuser and criminal copyright infringer. I don't give a damn about GitHub, this Microsoft trash.

**Comment by filips123** [comment]
They don't remove accounts that don't violate ToS. They remove accounts that violate ToS.

**Comment by ghost** [comment]
They remove everything! Even if just one person report anything he don't like, Microsoft will jump on it and ban the reported account without any question or notification!

**Comment by ghost** [comment]
**Don't you feel shameful that ZeroNet which claims to be "censorship-resistant" reporting accounts, banning accounts, hiding and discrediting pull request, violating licenses and copyrights of many people?** 

How is that? Tell me because I fail to understand!

**Comment by purplesyringa** [comment]
@CyberSecurityEngineer Sure! Feel free to report me if you want to.

**Comment by purplesyringa** [comment]
We are not shameful for reporting users who are attacking us as a project and personally instead of making a discussion.

**Comment by ghost** [comment]
Attacking us as a project? :rofl: You are a joke! Microsoft sucker! Is this your answer to a very embarrassing question?

**Comment by purplesyringa** [comment]
That's the best answer I could find for you, given that you didn't react to my "words are not contributions" phrase. Please elaborate on your views.

**Comment by filips123** [comment]
Yes. Microsoft sucker that made decentralized GitHub and GitLab alternative.

**Comment by ghost** [comment]
Pretending to be the victim? :rofl: What a fucking joke are you? You are nothing more than a bunch of criminals who still in this moment violates many licenses and copyright other many people including me! Shame on you, retarded maniac!

**Comment by purplesyringa** [comment]
I am working on MIT-licensed library alternatives right now. And what have you done to fix license problems?

**Comment by ghost** [comment]
I do like @imachug! He is great! I seen the `gitcenter` what he created! The only problem is the **centralized** zeroid which is required to use the gitcenter.

**Comment by purplesyringa** [comment]
ZeroNet does not support a better solution now. KxoID hasn't existed back then.

**Comment by filips123** [comment]
@imachug Can you add KxoID? Look, the first step into making new version :)

**Comment by purplesyringa** [comment]
I'd like to but I'm afraid I don't have some of Git Center keys anymore. I'll try to find them soon though.

**Comment by ghost** [comment]
> And what have you done to fix license problems?

I sent now the second pull request with the correct license and I was who informed this project about the problems regarding the licenses.

> ZeroNet does not support a better solution now. KxoID hasn't existed back then.

I think don't even need anything like this. Simply generate a key and give that to the user to save it, if they loosing the key, they loosing the repository. That simple. 

The key should be something like this: 255 random ASCII printable characters

**Comment by purplesyringa** [comment]
That's *not* simple. First, that's not supported by ZeroNet. Second, that doesn't solve spam problems.

**Comment by ghost** [comment]
A spammer will not contribute anything to a repository, so you can say that newly created repositories in X time should have X commit or will be deleted automatically. Spam solved.

**Comment by purplesyringa** [comment]
That's even more centralization, lol.

**Comment by ghost** [comment]
> That's even more centralization, lol.

**Automatization** is not centralization.

**Comment by purplesyringa** [comment]
Ok, so thinking more about it: spammers can easily abuse this by making a single commit every day.

**Comment by CyberSecurityEngineer** [comment]
Closing this. I'm happy that I was able to help ZeroNet even with just fixing MIME types and other things.

**Comment by ghost** [comment]
It is possible that there are other problems with MIME types: https://github.com/HelloZeroNet/ZeroNet/issues/2297 , https://github.com/HelloZeroNet/ZeroNet/issues/2297

**Comment by ghost** [comment]
@imachug mentioned here: https://github.com/HelloZeroNet/ZeroNet/issues/2241#issuecomment-546195188

> Hm, it looks like we're detecting mimetypes incorrectly. #1950 might help but it's for Python 2. I'll try to port it to Python 3 for tests. It'd also help if you run assoc in console and posted output here.

**Comment by ghost** [comment]
I going to look into this, yesterday tested the MIME type `video/mp4` but was failed. Videos can't be played even if they correctly signed and included in `content.json`.

**Pull request closed without merging**
