### PR TITLE
Close WebSocket connection gracefully

### PR DESCRIPTION
**Pull request by TheNain38**

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Does it helps your problem?

**Comment by TheNain38** [comment]
No, but it's always better to gracefully close a connection

**Comment by HelloZeroNet** [comment]
I think its better let the browser handle the connection. (close might be not compatible with every browser: http://stackoverflow.com/questions/5545161/unable-to-close-websocket-with-javascript)

**Comment by TheNain38** [comment]
Ok, so you close it?

**Comment by HelloZeroNet** [comment]
Yeah, i think we can close it

**Pull request closed without merging**
