### PR TITLE
Partly implement multisig

### PR DESCRIPTION
**Pull request by purplesyringa**
Signs with keys are now saved. `signs_required` is checked.

### CODE REVIEW

**Comment by imachug** [comment]
By the way, @HelloZeroNet.

Say, we have the following `content.json`:
```json
{
    ...
    "signers": [
        "A",
        "B"
    ],
    "signs": {
        "A": "Sign-for-version-1",
        "B": "Sign-for-version-1"
    },
    "signers_required": 2
    ...
}
```

Then, `A` adds new post:
```json
{
    ...
    "signers": [
        "A",
        "B"
    ],
    "signs": {
        "A": "Sign-for-version-2",
        "B": "Sign-for-version-1"
    },
    "signers_required": 2
    ...
}
```
...and tries to publish it. But he can't! All peers reject this `content.json` because only 1 sign (`A`) is valid. How can `B` get this `content.json` and sign it with his `B` key?

**Comment by HelloZeroNet** [comment]
Unfortunetly I think we can't avoid it... A has to send the content.json directly to B before it can publish to other peers.

**Comment by rllola** [comment]
There is no way to doing it with Zeronet ? You necessarily need to send it manually ? This might be annoying for users to do it everytime.

**Comment by krixano** [comment]
One way that would help this is if the content.json was in version control. Then, B could pull the latest commit made by A and sign and publish. Still a bit annoying I suppose.

**Comment by Thunder33345** [comment]
maybe for it to hold two versions of the site?
a signer pending version? where only content.json is downloaded and shared, when B gets it he can decide to sign or not while staying anonymous

**Comment by DaniellMesquita** [comment]
@krixano

> One way that would help this is if the content.json was in version control. Then, B could pull the latest commit made by A and sign and publish. Still a bit annoying I suppose.

Not so annoying if it implements archival features, likes IPFS haves.

@imachug
Could PeerMessage plugin help it?
What do you think about a archive plugin?

**Comment by purplesyringa** [comment]
I guess I'll close this PR because it doesn't address many problems and doesn't add any features.

**Pull request closed without merging**
