### PR TITLE
 Replacing incompatible GPLv2 license with GPLv3+ as contributors have agreed!

### PR DESCRIPTION
**Pull request by ghost**
Most contributors voted for GPLv3+ at https://github.com/HelloZeroNet/ZeroNet/issues/2273 before two contributors have manipulated the voting. I herein sending the new license. 

The voting result is confirmed by @HelloZeroNet at https://github.com/HelloZeroNet/ZeroNet/issues/2273#issuecomment-559163860.

I was who reported the licensing issue and the voting is ended so I demand to merge my contribution or you legally required to remove my contributions from UiRequest.py what you also merged in your own name! 

I contributed to ZeroNet and no credit is given to me and now I send again a contribution which you closed because "you want to do by yourself again" changes which based on my contribution. Either you remove all my contributions from UiRequest.py or you merge this pull request and give me credit for this and all previous contributions! 

**You are not allowed to copy my contributions and merge it in your name!**

### CODE REVIEW

**Comment by ghost** [comment]
I warning you that I will distribute ZeroNet under GPLv3+ no matter what you do! I do follow the voting results which clearly indicated that most contributors want GPLv3+. Under the GPLv3 license you are not allowed to close pull request and merge it in your name! Please remove my contributions from UiRequest.py before you close these pull request again! I warning you I will sue you personally if you later replace the license in your name or if you put any other license on ZeroNet than GPLv3+!

**Comment by HelloZeroNet** [comment]
The voting majority should be based on number of active lines in the repository. I have not seen these kind of statistics, so I have not decided yet if I pick GPL3/GPL3+/MIT or any other license.

But once I do, I will update the license myself to avoid future drama.

You are feel free to do what you want all code I have written is licensed under CCZERO. I not doing this to receive any kind of fame.

**Comment by ghost** [comment]
You don't own ZeroNet and I'm a contributor. I demand that you replace the license with GPLv3+!

**Comment by filips123** [comment]
> You don't own ZeroNet

Yes? How? And where is the problem now?

**Pull request closed without merging**
