### PR TITLE
Add a prototype.json

### PR DESCRIPTION
**Pull request by tangdou1**
Add a prototape.json for other languages to check update in SideBar

### CODE REVIEW

**Comment by tangdou1** [comment]
Thanks. Hope HelloZeroNet would accept it.

**Comment by krixano** [comment]
Why did you close this if you want it accepted?

**Comment by HelloZeroNet** [comment]
Probably it would be better to generate it automatically as it could be a pain to keep it up to date.

**Comment by tangdou1** [comment]
Yes, it would be a pain. However, I do not have these techniques to generate it automatically. How about close it？

**Pull request closed without merging**
