### PR TITLE
IPV6 Supports in the smallest code change

### PR DESCRIPTION
**Pull request by tangdou1**
If you can not wait the official ipv6 support, you can use ipv6 version directly replacing the core code (see: zihu.bit/?Topic:1537342516_1K7tW4WEbso38uMs4RN3W7GihA6tTqrApz/+IPV6) (And I delete the original source in github because zeronet would transfer to Python3 and many codes would change, this PR would be just a reference for Python3.)
IPV6 Supports: 
(If you donot have ipv6, these change would not change the logic of your code. If you have public ipv6, these change would let you choose ipv6 as your connection server first (can let the users to choose if needed ), not your public ipv4 address, in which you can also connect these ipv4 peers and ipv4 trackers. )

- [x] UDP/TCP Trackers Supports

- [x] Peer Exchange Supports

- [x] BigFile Supports

- [x] Bootstrapper Supports

- [x] Tested in real condition

### CODE REVIEW

**Comment by DaniellMesquita** [comment]
@tangdou1
What the previous pull request haves that was removed in this other?

**Comment by DaniellMesquita** [comment]
Please tell when this is ready to be merged.

**Comment by tangdou1** [comment]
> 
> 
> @tangdou1
> What the previous pull request haves that was removed in this other?

Because it has a conflic file and some redundant changes when the zeronet update to 3609.

**Comment by tangdou1** [comment]
> 
> 
> Please tell when this is ready to be merged.

It can works now. You should ask HelloZeroNet when to merge and whether I need more changes for his preferable code style.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by DaniellMesquita** [comment]
@april93 @blurhy

**Comment by tangdou1** [comment]
You mean the test file in Test folder should also be modified based on ipv6? And the openport check before connection server starting is just used for share its own ipv6 bootstrapper because the adding my own bootstrapper function is binded on the openport function.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
> Thanks for the PR, I won't be around in the next weeks, but I will check it after. New test cases, benchmarking ipv6 address packing/unpacking will be necessary and port open check before starting the file server probably breaks multiple things.

Another pull request you will left open?

**Comment by DaniellMesquita** [comment]
@tangdou1
Your other pull request was working, but this not.

**Comment by DaniellMesquita** [comment]
- [ ] Fix: it is only showing own IPv6 on trackers, but not when IPv4
- [ ] After CJDNS closed (IPv6 address), it turns into IPv4. Listen for when IPv6 is available again, then turn into IPv6
- [ ] Fix: CJDNS needs to be openned when ZeroNet is closed, or it will have conflict

**Comment by tangdou1** [comment]
> 
> 
> @tangdou1
> Your other pull request was working, but this not.
> Note: I disable Tor, and it began working.

I donot realise the tor function in IPV6 now.

**Comment by DaniellMesquita** [comment]
@tangdou1
Even disabling Tor, can connect to peers that uses it?

**Comment by DaniellMesquita** [comment]
After some time, it switchs from IPv6 to IPv4.

**Comment by tangdou1** [comment]
> 
> 
> After some time, it switchs from IPv6 to IPv4 as main IP.

Fix it now.

> 
> 
> @tangdou1
> Even disabling Tor, can connect to peers that uses it?
Not, if you disable Tor, you can not connect peers using Tor. I mean I donot know if you open tor, you can connect ipv6 users using Tor , but you can also connect ipv4 users using Tor.

**Comment by DaniellMesquita** [comment]
Thanks for the fix.
But my IPv6 is changing to another IPv6 address, and ZeroNet is keeping the old one.

**Comment by DaniellMesquita** [comment]
Weird: I restarted ZeroNet, and it returned to the old IPv6 and working, but the new IPv6 was working before.

**Comment by DaniellMesquita** [comment]
@tangdou1

**Comment by tangdou1** [comment]
> 
> 
> Weird: I restarted ZeroNet, and it returned to the old IPv6 and working, but the new IPv6 was working before.

Because zeronet do not save your external ipv6 or ipv4 address in .conf file, just save your port in it.

**Comment by DaniellMesquita** [comment]
> Conflicting files
> src/Config.py

@tangdou1 
Please can you solve this conflict?
So I can update ZeroNet, since here is a security flaw that @shortcutme fixed, reported by @krixano and @imachug.

**Comment by DaniellMesquita** [comment]
@tangdou1 
I think he only returned to fix the critical security flaw, but is yet on vacation.
@shortcutme

**Comment by imachug** [comment]
@DaniellMesquita No, he was in the airport when he answered to our mail.

**Comment by DaniellMesquita** [comment]
@tangdou1 
Ready to be merged?

@shortcutme 
Is you committed to review it?

**Comment by DaniellMesquita** [comment]
For who need a IPv6 tracker: `fc81:4668:5a19:0c29:9dfe:ed94:d745:85c9`

**Comment by HelloZeroNet** [comment]
Yeah I will check and test it in the following days

**Comment by krixano** [comment]
I get this error when clicking "Re-check open port". Not sure if it's related to this, but it only happened after I downloaded this pr:

> Internal error: TypeError: argument of type 'NoneType' is not iterable
UiWebsocket.py line 81 > UiWebsocket.py line 267 > UiWebsocket.py line 987 > AnnounceSharePlugin.py line 173 > FileServer.py line 130

**Comment by styromaniac** [comment]
After I add the patch on Android, I'm unable to set a custom file server port in zeronet.conf via text editor. Also note that rev3616 broke the /Config page being able to save a custom file server port to zeronet.conf

**Comment by styromaniac** [comment]
Same exact bug as krixano explained, and he looked into it because I mentioned it.

**Comment by styromaniac** [comment]
Other issue: I tested an IPv6 tracker and it gets 0% success, doesn't read the first colon of the IP address, so the remainder is cut off in ZeroHello.

**Comment by krixano** [comment]
Here's my IPv6 on CJDNS: fc36:b408:aecd:ecca:7c32:d6e1:f9dd:78b2

**Comment by tangdou1** [comment]
> 
> 
> I get this error when clicking "Re-check open port". Not sure if it's related to this, but it only happened after I downloaded this pr:
> 
> > Internal error: TypeError: argument of type 'NoneType' is not iterable
> > UiWebsocket.py line 81 > UiWebsocket.py line 267 > UiWebsocket.py line 987 > AnnounceSharePlugin.py line 173 > FileServer.py line 130

Fix it now

**Comment by styromaniac** [comment]
DaniellMesquita, I have an IPv6 address on this network, but as for CJDNS, I've looked around and hadn't found prebuilt APKs.

**Comment by DaniellMesquita** [comment]
@tangdou1 
http://ipv6.tracker.harry.lu:80/announce isn't working.

@krixano 
Your IPv6 tracker is also not working here.

Please test if my tracker is working: `zero://fc81:4668:5a19:0c29:9dfe:ed94:d745:85c9`

@styromaniac
https://github.com/cjdelisle/cjdns/tree/master/contrib/android

**Comment by DaniellMesquita** [comment]
@styromaniac
Connect to my tracker now and tell if is working?

Can you enable bootstrapper plugin and share the IPv6 address? Is it fixed?

**Comment by DaniellMesquita** [comment]
Uploaded this IPv6 patch with latest ZeroNet updates, on IFS:

http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1Mz1_15hL2gR4oCSgKBbndn3MxY8Hc5xoy1vqCe_item_2+type:archive

**Comment by krixano** [comment]
> @tangdou1
> http://ipv6.tracker.harry.lu:80/announce isn't working.
> 
> @krixano
> Your IPv6 tracker is also not working here.
> 
> Please test if my tracker is working: `zero://fc81:4668:5a19:0c29:9dfe:ed94:d745:85c9`
> 
> @styromaniac
> https://github.com/cjdelisle/cjdns/tree/master/contrib/android

...Because I was still on the old patch... that didn't work...

**Comment by April93** [comment]
>http://ipv6.tracker.harry.lu:80/announce isn't working.

That's because you don't have ipv6. Cjdns alone won't connect you to that tracker.

>but as for CJDNS, I've looked around and hadn't found prebuilt APKs.

AFAIK there's no apk.

**Comment by krixano** [comment]
@April93 Because that tracker doesn't use cjdns, right? Cjdns cannot connect to non-cjdns ipv6 addresses. And non-cjdns clients cannot connect to cjdns ipv6 addresses.

Also, can you test my tracker if you have the time?

**Comment by krixano** [comment]
@styromaniac was wondering if you needed to add brackets with the ip inside, because that's how a lot of ipv6 addresses are typed in. Also, doing this (adding the brackets) makes the tracker not show up in the trackers list anymore.

**Comment by DaniellMesquita** [comment]
@krixano
Thanks for reposting things from [this topic](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1538505571_15hL2gR4oCSgKBbndn3MxY8Hc5xoy1vqCe) here.

I can't connect to your tracker, even we both using CJDNS.
Also, now my tracker is showing error.

**Comment by DaniellMesquita** [comment]
ZeroHello could show the network of trackers (IPv4, Tor, IPv6, CJDNS).
Also, does the Config with trackers haves support to comments? For sample:

> zero://fc36:b408:aecd:ecca:7c32:d6e1:f9dd:78b2 #CJDNS
> zero://fc81:4668:5a19:0c29:9dfe:ed94:d745:85c9 #CJDNS
> http://0d.kebhana.mx:443/announce #IPv6
> udp://tracker.torrent.eu.org:451/announce #IPv6
> udp://tracker.cypherpunks.ru:6969/announce #IPv6
> http://torrent.nwps.ws:80/announce #IPv6
> http://ipv6.tracker.harry.lu:80/announce #IPv6

**Comment by DaniellMesquita** [comment]
@krixano @tangdou1
Does you have profile on Keybase?

**Comment by krixano** [comment]
> I can't connect to your tracker, even we both using CJDNS.
Also, now my tracker is showing error.

I'm currently at school now, so my tracker won't work right now.

@tangdou1 You should be able to mark this as off topic to hide it I think.

**Comment by DaniellMesquita** [comment]
@tangdou1 

Suggestion:
Use IPv4 to connect IPv4, IPv6 to connect IPv6 and CJDNS to connect CJDNS, or is it already working at this form?

**Comment by styromaniac** [comment]
I hope there's some way to pair IPv4 and IPv6 addresses together without resorting to domain names, so then the same bootstrap node isn't queried twice if both addresses are available. Does ZeroNet avoid use of IPv4 while using IPv6?

**Comment by DaniellMesquita** [comment]
IPv6 needs to be preferable

**Comment by styromaniac** [comment]
Maybe instead of hashtagging, have each type of tracker (IPv4, Tor, IPv6, CJDNS) in separate categories and have ZeroNet choose the category that fits its networking configuration. Make separate input boxes on /Config by category. That would be less text in a json file and eliminate useless information on ZeroHello.

**Comment by DaniellMesquita** [comment]
I think every tracker is needed, but user should prioritize trackers. For sample, prioritize trackers with zero:// protocol.

And Config for bootstrapper, where tracker owner can setup multiple trackers:

- [ ] IPv4
- [ ] Tor
- [ ] IPv6
- [ ] CJDNS

**Comment by znwulf** [comment]
You're probably more likely to be able to directly connect to a peer over IPv6 than with IPv4 due to its independence from NAT, so I would prioritise IPv6 trackers, especially for initial bootstrap. 

Obviously if 6 isn't enable on the host a check could be implemented to skip those trackers, and it shouldn't interfere with CJDNS trackers since CJDNS doesn't use properly assigned IPv6 address space and are thus easy to identify.

**Comment by styromaniac** [comment]
@znwulf That sounds good, or perhaps have each tracker give a hash or name, then when IPv4 and IPv6 addresses are found to have the same ID or name, prefer it's IPv6 address. I don't know which will be more efficient.

**Comment by znwulf** [comment]
@styromaniac By the looks of the bittorrent protocol spec the clients should announce the IPs they're reachable via. I'm going to build a tracker in python that supports v4 and v6 announcements in case people want to run trackers to make their dual-stacked clients discoverable.

**Comment by DaniellMesquita** [comment]
> Obviously if 6 isn't enable on the host a check could be implemented to skip those trackers
Don't skip if trackers supports both IPv4 and IPv6.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
Could you f****ng review this pull request? Could you f****ng study about i2P after implementing PY 3, as @MuxZeroNet already pointed out that you're wrong about the difficulties to implement it alongside Tor?

image
image
image

Do you know that Get Games has been recently removed?
You said ZeroNet zites are uncensorable. News sites said that Play can't be put down.

getgames

In fact, a zite can't be destroyed because other users seeds it, but a zite content can be removed and users misses it. YOU SHOULD IMPLEMENT AN ARCHIVING PLUGIN, LIKE IPFS DOES!

**Comment by DaniellMesquita** [comment]
@imachug

**Comment by tangdou1** [comment]
Good news for the official ipv6 support.

**Comment by HelloZeroNet** [comment]
Yeah thanks again for pr, I used many part from it

**Pull request closed without merging**
