### PR TITLE
Sign & Publish in one button

### LINKED ISSUE #1229: [suggestion] Sign & Publish in one button?
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0 rev3178
  * Operating system: Windows 10
  * Web browser: Tor borwser
  * Tor status: always

### Step 2: Describe the problem:

When i do "Publish" (without "Sign"), it tells me: "Content published to 5/5 peers." which mislead me into believing changes was published to all people.
If i have to do "Sign" before "Publish" then i think it should tell me: "You have not signed changes, content was not published to peers." Why it should tell me publishing was done if there was no signed changes so nothing new was published to peers?
It may be helpfull if the button is more noob friendly like [ Sign & Publish changes ] or the notification popup messages more talkative so even noob knows what to do.
Thank You

### PR DESCRIPTION
**Pull request by imachug**
Closes #1229

### CODE REVIEW

**Comment by krixano** [comment]
What final result looks like:
image

image

**Comment by krixano** [comment]
Looks like the `src/Test/TestRateLimit.py::TestRateLimit::testCall FAILED                [ 49%]` test failed.

**Comment by imachug** [comment]
@krixano lemme check.

**Comment by imachug** [comment]
That check is about how much time some op takes. So that's not important in this case as I didn't edit that part of code.

**Comment by anoadragon453** [comment]
Using the same dropdown code as ZeroHello might be a good idea, and look cleaner. It does use a ⋮ instead of an arrow but that could work as well.

**Comment by imachug** [comment]
@anoadragon453 I tried to find other buttons which look the same way, but didn't manage to do that. So maybe a dropdown would be better, right.

**Comment by imachug** [comment]
Though I am not sure what would be better. @HelloZeroNet, do you allow me to bring yet-another-library to Sidebar plugin?

**Comment by HelloZeroNet** [comment]
Imachug: I would prefer to use the current ones. ZeroTalk has a jquery compatible version of the dropdown menu. I think that would be the best to use to keep the UI consistency.
https://github.com/HelloZeroNet/ZeroTalk/blob/master/css/Menu.css
https://github.com/HelloZeroNet/ZeroTalk/blob/master/js/utils/Menu.coffee
https://github.com/HelloZeroNet/ZeroTalk/blob/master/js/TopicList.coffee#L260
https://github.com/HelloZeroNet/ZeroTalk/blob/master/index.html#L179

**Comment by imachug** [comment]
@HelloZeroNet Did you get a letter from `saketjoshiiit [at] gmail [dot] com`? Kinda spam?

**Comment by imachug** [comment]
@HelloZeroNet I'll use that library then.

**Comment by HelloZeroNet** [comment]
I have no email from saketjoshiiit

**Comment by imachug** [comment]
@HelloZeroNet 

> Hello,
> 
> I am a university researcher working on an empirical study of software
> projects. A part of my study concerns projects with high release
> rates.I noticed that the software repository HelloZeroNet/ZeroNet on
> Github has a very fast release cycle. If you couple quickly answer a
> couple of questions below and reply to me at the earliest, that would
> be very helpful.
> 
> Q1. Would you say the repository development is in a sense 'agile',
> i.e. is rapid development being done?
> Q2. What kind of a project is this? e.g (Web application, driver, e.t.c)
> Q3. Is there any reason for rapid releases? i.e. do you have
> auto-release set, are changes done in between releases, e.t.c
> 
> Both, a brief reply to the questions, and if you wish any other
> comments are welcome.
> Also, it would be helpful if you could mention the repository name in
> your reply for my convenience.
> 
> Thank you,
> Saket Joshi

**Comment by imachug** [comment]
@HelloZeroNet Updated

image

**Comment by imachug** [comment]
@HelloZeroNet Sorry, can we merge this?

**Comment by HelloZeroNet** [comment]
Currently I made some changes on sidebar. I'm going to publish a new version in the next days after that I will check it.

**Pull request merged**
