### PR TITLE
Segmentation fault with latest greenlet

### PR DESCRIPTION
**Pull request by JabbaDesilijicTiure**
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
Segmentation fault

### CODE REVIEW

**Comment by JabbaDesilijicTiure** [comment]
@imachug @HelloZeroNet go ahead and verify it.

**Comment by jamadden** [comment]
On Python 3.7 and above, using greenlet 0.4.17 requires gevent 20.9.0.

**Comment by JabbaDesilijicTiure** [comment]
@jamadden I tested and I got this with gevent 20.9.0: 
    thread_result.set(func(*args, **kwargs))
TypeError: get() missing 1 required positional argument: 'cookie'

**Comment by JabbaDesilijicTiure** [comment]
@imachug can you look into this issue please?

**Comment by jamadden** [comment]
Without any sort of traceback, I don't know what to tell you about that exception.

**Comment by JabbaDesilijicTiure** [comment]
@jamadden 

Traceback (most recent call last):
  File "/opt/z/environment/lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
TypeError: get() missing 1 required positional argument: 'cookie'
2020-09-23T12:52:47Z (<ThreadPoolWorker at 0x7f868ae630f0 thread_ident=0x7f868a9e4700 threadpool-hub=<Hub at 0x7f868aea9a00 thread_ident=0x7f868d90b740>>, <bound method Queue.get of <gevent._threading.Queue object at 0x7f868a9f3480>>) failed with TypeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/opt/z/src/util/ThreadPool.py", line 148, in run
    func, args, kwargs, event_done = self.pool.apply(self.queue_call.get)
  File "/opt/z/environment/lib/python3.8/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/opt/z/environment/lib/python3.8/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "/opt/z/environment/lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
TypeError: get() missing 1 required positional argument: 'cookie'
2020-09-23T12:52:47Z <Greenlet at 0x7f868aedf6a0: <bound method MainLoopCaller.run of <util.ThreadPool.MainLoopCaller object at 0x7f868aeca700>>> failed with TypeError

**Comment by jamadden** [comment]
Prior to https://github.com/HelloZeroNet/ZeroNet/commit/ea6016d004eeb1c8f2927d171fae615d1afc7d8e#diff-71a02f5e0de4b6dc6aaa7cdeba68f649, `ZeroNet.util.ThreadPool` was using undocumented gevent internals that have changed in an incompatible way.

**Comment by JabbaDesilijicTiure** [comment]
@jamadden thank you

**Pull request closed without merging**
