### PR TITLE
Add allow-same-origin to sandbox iframe

### PR DESCRIPTION
**Pull request by ceritium**
Allow access to methods of `window.parent.location` like `hash` or `query`.

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
every zeronet site is running from the same domain (127.0.0.1), so it would be a security issue to allow same origin access, but you can modify the hash/query using `window.top.location = "?something#hello2"`
or wrapperPushState/wrapperReplaceState zeroframe api commands

**Comment by ceritium** [comment]
You are right, it is a security issue.

As you said I can modify the hash/query with `window.top.location = "?something#hello2"` but I am not able to read the value of hash/query.

screen shot 2016-10-19 at 23 36 32


What do you suggest?

**Comment by HelloZeroNet** [comment]
you able to reach the get parameters directly, using window.location.search (you need to remove `wrapper_none=.*`)
if you call `Page.cmd("innerLoaded")` command the hash will be applied to the inner frame, so you can reach it using window.location.hash
```
> window.location.search
< "something&wrapper_nonce=22f998ea92f1e2574c72cdc96ba7d479d9c1aec8fa31e3873047cbb61987f784"
> window.location.hash
< ""
> Page.cmd("innerLoaded")
> window.location.hash
< "#hello"
```

**Comment by ceritium** [comment]
Thank you very much for the answers: D

**Pull request closed without merging**
