### PR TITLE
Pass #hash to inner iframe on load

### PR DESCRIPTION
**Pull request by imachug**
See #914

### CODE REVIEW

**Comment by mishfit** [comment]
While I like the idea of pushing the hash to the client I think it shouldn't be in the template for the wrapper, but instead somewhere in the [javascript portion of the logic for the wrapper](https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/media/Wrapper.coffee#L372-L380):
```javascript
# Iframe loaded
	onLoad: (e) =>
		@inner_loaded = true
		if not @inner_ready then @sendInner {"cmd": "wrapperReady"} # Inner frame loaded before wrapper
		#if not @site_error then @loading.hideScreen() # Hide loading screen
                //# ***NOTE***
                // somewhere in here the hash should be pushed to the inner_frame
                //***
		if @ws.ws.readyState == 1 and not @site_info # Ws opened
			@reloadSiteInfo()
		else if @site_info and @site_info.content?.title?
			window.document.title = @site_info.content.title+" - ZeroNet"
			@log "Setting title to", window.document.title
```
This would keep the logic in the same file as [this](https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/media/Wrapper.coffee#L29-L33) (which handles hash changes):
```javascript
window.onhashchange = (e) => # On hash change
			@log "Hashchange", window.location.hash
			if window.location.hash
				src = $("#inner-iframe").attr("src").replace(/#.*/, "")+window.location.hash
				$("#inner-iframe").attr("src", src)
```

**Comment by HelloZeroNet** [comment]
This is intentionally: like @mishfit pointed out you have to call the wrapperReady api request, because if you have dynamic page you need to load resources to render the page before you can scroll to the anchor

**Comment by imachug** [comment]
BTW, sometimes the inner iframe reloades on hashchange. What about changing:
```javascript
src = $("#inner-iframe").attr("src").replace(/#.*/, "")+window.location.hash
$("#inner-iframe").attr("src", src)
```
to:
```javascript
$("#inner-iframe").attr("src", window.location.hash)
```

Is there any reason why ```src``` is changed instead of hash?

**Comment by imachug** [comment]
Well, I think, that's my fault. I didn't know that `wrapperInnerLoaded` is a valid command itself. For me, [ZeroFrame API Reference on readthedocs.io](https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/) was the best reference, but `wrapperInnerLoaded` section appeared *after* I found this issue.

**Pull request closed without merging**
