### PR TITLE
Added Contribution License Guidelines

### PR DESCRIPTION
**Pull request by canewsin**

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks, I think it would be more proper to add it to the LICENSE file

**Comment by canewsin** [comment]
Added in
https://github.com/HelloZeroNet/ZeroNet/pull/2496

**Comment by ghost** [comment]
Take a look at this: https://github.com/HelloZeroNet/ZeroNet/issues/2273#issuecomment-606639653

**Comment by HelloZeroNet** [comment]
Thanks, merged #2273

**Pull request closed without merging**
