### PR TITLE
Update UiRequest.py

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
For the downsides of this pr that have already been discussed, see #2248

**Comment by ghost** [comment]
> For the downsides of this pr that have already been discussed, see #2248

Get lost! You have nothing else to do?

**Comment by ghost** [comment]
Not *if* you're trying to cover up criticism by creating a new PR

**Comment by HelloZeroNet** [comment]
I have pushed modifications in Rev4250 that has updated list of bundled content types based on this PR and also solves the font loading problems.

Adding long cache values is not a great idea as the content can change any time.

**Comment by ghost** [comment]
Thanks @HelloZeroNet ! Just when I finished writing my own pr that's pretty much as simple as what you did, lol. The other PR at #2248 should also be closed.

**Pull request closed without merging**
