### PR TITLE
[WIP - depends on other pull request] Support Clipboard.js

### PR DESCRIPTION
**Pull request by DaniellMesquita**

### CODE REVIEW

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/pull/1680

**Comment by HelloZeroNet** [comment]
Not sure why would we need clipboard.js as it's pretty easy to do it without any external dependency: see the copy peers part of the sideboard

**Comment by DaniellMesquita** [comment]
Also, its weird to load clipboard.js on every site load

**Comment by DaniellMesquita** [comment]
@HelloZeroNet 
Implemented on this commit: https://github.com/HelloZeroNet/ZeroNet/pull/1680/commits/c29019102056bc210b44d6278360a88da4728b6d but didn't works

**Pull request closed without merging**
