### PR TITLE
Added P2P portcheck

### PR DESCRIPTION
**Pull request by grez911**
Issue: https://github.com/HelloZeroNet/ZeroNet/issues/80

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks, I think it would be better to use object as return of the actionCheckport request, use config.homepage instead of fixed site address and i'm not sure if socket.connect_ex does not leaks real IP address in tor mode.

**Comment by grez911** [comment]
> i'm not sure if socket.connect_ex does not leaks real IP address in tor mode.

@HelloZeroNet You do a [socket patch](https://github.com/HelloZeroNet/ZeroNet/blob/de550d7cae940630855a9466e88695f2b3a6a950/src/main.py#L137) in main.py if --tor always enabled, I think this will redirect all socket connections to Tor, but I will try to catch packets with Wireshark to be completely sure.

**Comment by grez911** [comment]
@HelloZeroNet, I did it! There are two pcap-files in [this archive](https://github.com/HelloZeroNet/ZeroNet/files/1232142/cap.zip) each of which contain packets recorded on the receiving end of the suspicious `socket.connect_ex` command.
One file contains capture for Tor only mode and another for default zeronet start without any parameters.
Just a little explanation, what I did. I opened port 4444 on my remote VPS with `nc -k -l -p 4444` command and in the other console on the VPS started dumping packets to file with `tcpdump dst port 4444 -w out.cap` command.
Small changes have been made in this pull request to force zeronet connect to 81.4.104.218:4444 instead of a random peer of HelloZeroNet page. Here the scheme:
```
+---------+ 93.84.53.139    Clearnet    81.4.104.218:4444 +-----+
| zeronet |---------------------------------------------->| VPS |
+---------+                                         ^     +-----+
      |                                             |
      | Tor    +-----------+ 176.126.252.12         |
      +------->| Exit node |------------------------+
               +-----------+
```
So you can open records with Wireshark and make sure that there is absolutely no records about my real IP (93.84.53.139) when Tor always enabled.

P. S. Object return and config.homepage I will add to the pull request later, please, wait.

**Comment by grez911** [comment]
@HelloZeroNet, all done. Is there anything else?

**Comment by HelloZeroNet** [comment]
Thanks!

**Pull request merged**
