### PR TITLE
Add Farsi (Persian) Translation to ZeroNet

### PR DESCRIPTION
**Pull request by Zaefarani**
Persian Translation of ZeroNet Site

### CODE REVIEW

**Comment by Zaefarani** [comment]
> Hello!
> 
> I'm happy to see a Farsi (Persian) translation! ❤️
> The only problem is the filename: ~fa,json~ it should be **fa.json**
> 
> I opened a pull request: [Zaefarani#1](https://github.com/Zaefarani/ZeroNet/pull/1)
Yes, You are right. I fixed that. hope that works
thanks for your remark

**Comment by Zaefarani** [comment]
> Hello!
> 
> I'm happy to see a Farsi (Persian) translation! ❤️
> The only problem is the filename: ~fa,json~ it should be **fa.json**
> 
> I opened a pull request: [Zaefarani#1](https://github.com/Zaefarani/ZeroNet/pull/1)

yes, you are right. I fixed that
thanks for your hint

**Comment by decentralizedauthority** [comment]
I have that feeling that @HelloZeroNet will not merge Persian or even Arabic because he a Hungarian racist. At least that what I find about Tamas Kocsis and ZeroNet online. Probably @imachug can confirm this.

**Comment by decentralizedauthority** [comment]
I will use your translation @Zaefarani because I know people who speak Persian and it is extremely useful that you translated ZeroNet for them! I can more easily explain to them how to publish on ZeroNet. Unfortunately I believe contributing to this repository is just a waste of time.

**Comment by decentralizedauthority** [comment]
@Zaefarani can you verify this text? https://github.com/HelloZeroNet/ZeroHello/commit/69876ff3fc8dc8a6bc1d6611ea794d2d5a5f85d9 I'm not sure that the Slovenia @filips123 speak Persian! :thinking:

**Comment by Zaefarani** [comment]
> @Zaefarani can you verify this text? [HelloZeroNet/ZeroHello@69876ff](https://github.com/HelloZeroNet/ZeroHello/commit/69876ff3fc8dc8a6bc1d6611ea794d2d5a5f85d9) I'm not sure that the Slovenian @filips123 speak Persian! 🤔

َActually I think when I published the translations in the ZeroNet forum asked by someone (not this name) they used and committed those words here.

**Comment by decentralizedauthority** [comment]
Basically they merged your work without giving you credit. Not cool from @filips123 and @HelloZeroNet ! I was thinking about that option that @filips123 asked you and voila, that is the case. 

This is not the first time that this repository copy from people and merging commits in they own name without giving credit to the originator! This must be avoided in the future or I will be forced to bring this to court!

**Comment by purplesyringa** [comment]
@HelloZeroNet ...

**Comment by purplesyringa** [comment]
> Basically they merged your work without giving you credit.

Basically, adding a person to CONTRBUTORS.md (e.g.) file is not the only way to give credit. We're using Git for version control and it includes commit authors and such, so everyone who uses ZeroNet source code has a list of all changes including contributor names.

**Comment by Zaefarani** [comment]
> Basically they merged your work without giving you credit. Not cool from @filips123 and @HelloZeroNet ! I was thinking about the option that @filips123 asked you and voila, that is the case.
> 
> This is not the first time that this repository copy from people and merging commits in their own name without giving credit to the originator! This must be avoided in the future or I will be forced to bring this to court!

I think there was chaos in the English forum when Iranians entered there and it's possible that they didn't know that I have an active Github account. so for speeding things up they did that on my behalf and I don't have any problem with that. actually what's more important here is Iranians access to these places so they could communicate with each other in internet breakdowns.

**Comment by decentralizedauthority** [comment]
I'm also a contributor better you not forget that!

**Comment by decentralizedauthority** [comment]
> I think there was chaos in the English forum when Iranians entered there

I wonder what kind of chaos you referring to.. Islamophobia?  

> actually what's more important here is Iranians access to these places so they could communicate with each other in internet breakdowns

I 100% support the Iranian government to block DNS access to twitter, facebook and other U.S. based services. Also we should not leave out from the story that the Iranian government arrested CIA affiliated people who actually responsible for those riots. 

If people want to riot against something than riot against the sanctions imposed by the United States on Iran because exactly that is the reason that the fuel prices risen. Iran is surrounded by U.S. military bases and they goal is exactly what was in Syria. Right now in Syria the United States occupied by military force the oil fields and looting it. 

I support any movement which is against the United States of America and I actually use ZeroNet against the CIA and other departments under the wings of Pentagon. Long live Iran! Long live everyone who fight against the United States, NATO and other trash. So yeah, shutdown Twitter, WikiPedia and other services based in the United States.

**Comment by HelloZeroNet** [comment]
Thanks

**Pull request merged**
