### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by iFallenHunt**

### CODE REVIEW

**Comment by canewsin** [comment]
This Repo is Not Maintained Anymore.
Make a Pull Request to https://github.com/ZeroNetX/ZeroNet

**Comment by caryoscelus** [comment]
@iFallenHunt now this looks more like a translation commit ;_) please note that README has been updated in https://github.com/zeronet-conservancy/zeronet-conservancy , but we would welcome your translation !

**Comment by iFallenHunt** [comment]
> 

got it, sorry I'm new to git and I'm still understanding how some things work, but I feel interested in contributing with some things I already have, like translations. how can I submit this translation?

**Comment by caryoscelus** [comment]
@iFallenHunt if you will translate up-to-date README.md of https://github.com/zeronet-conservancy/zeronet-conservancy , i will gladly guide you through the process

**Comment by iFallenHunt** [comment]
> 

@caryoscelus perfect, I will create a fork of https://github.com/zeronet-conservancy/zeronet-conservancy and add the file, I can do more translations if it is useful

**Comment by caryoscelus** [comment]
@iFallenHunt thank you ! looking forward to it

**Pull request closed without merging**
