### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by ghost**
Travis here: https://github.com/HelloZeroNet/ZeroNet/pull/2522#issuecomment-612655676 used a cached version of gevent but we want this: https://github.com/HelloZeroNet/ZeroNet/pull/2522#issuecomment-612658601 (don't use pip cache) 
@imachug just pointed out here https://github.com/HelloZeroNet/ZeroNet/pull/2522#issuecomment-612665000 that;

> The problem is when gevent-1.4.0 is already cached (e.g. gevent was installed when 1.5.0 wasn't available yet). 

--upgrade --no-cache-dir :thinking: :+1:

### CODE REVIEW

**Comment by purplesyringa** [comment]
Do you understand that this only "fixes" the problem on Travis but not on users' machines? Perhaps specifying the correct versions we actually need, not making pip guess what we want is the correct way.

**Comment by ghost** [comment]
> Do you understand that this only "fixes" the problem on Travis but not on users' machines? Perhaps specifying the correct versions we actually need, not making pip guess what we want is the correct way.

@imachug we discussed this with @filips123 before, **installing gevent 1.4.0 support those versions of python which are not supported by gevent 1.5.0!** The users you talk about will download and install ZeroNet so users will have a fresh install by pip with the **correct version of gevent**!  

Totally unnecessary and be clear, it is also stupid to have anything more in requirements.txt than **gevent>=1.4.0** :+1:

**Comment by purplesyringa** [comment]
Again. Please install `gevent>=1.4.0` for old Python versions and `gevent>=1.5.0` for new Python versions. The reasoning is: pretend someone uses a new Python version but they have installed gevent before 1.5.0 was published. In this case, installing requirements.txt will still use gevent 1.4.0. In case of PyPy this means breaking ZeroNet.

**Comment by ghost** [comment]
> Again. Please install `gevent>=1.4.0` for old Python versions and `gevent>=1.5.0` for new Python versions. The reasoning is: pretend someone uses a new Python version but they have installed gevent before 1.5.0 was published. In this case, installing requirements.txt will still use gevent 1.4.0. In case of PyPy this means breaking ZeroNet.

@imachug 
Nobody installed gevent 1.4.0 before! You know why? Because, **requirements.txt had a version of 1.1.0 in ZeroNet for years!** If someone has lower version than 1.4.0, requirements.txt will upgrade it!

**Comment by HelloZeroNet** [comment]
It should work as it is now.

**Pull request closed without merging**
