### PR TITLE
Update all.js

### PR DESCRIPTION
**Pull request by tangdou1**

### CODE REVIEW

**Comment by blurHY** [comment]
It's compiled from coffee script.So maybe you should edit the coffee script files

**Comment by tangdou1** [comment]
> 
> 
> It's compiled from coffee script.So maybe you should edit the coffee script files

Coffee has been changed, however js keep unchanged.

**Comment by blurHY** [comment]
@shortcutme Did you compile these coffee files

**Comment by HelloZeroNet** [comment]
Not sure what happened, but thanks

**Pull request merged**
