### PR TITLE
set stack_size for router #627

### PR DESCRIPTION
**Pull request by cxgreat2014**
#627

### CODE REVIEW

**Comment by cxgreat2014** [comment]
Um..If it can't start thread, it will show error to me, but works fine...

**Comment by cxgreat2014** [comment]
image
without any error
image

**Comment by ysc3839** [comment]
I mean if the thread works well on current OS. It's no need to change the stack size.

**Comment by cxgreat2014** [comment]
Yes, you are right...But how to check it?

**Comment by ysc3839** [comment]
#780

**Comment by cxgreat2014** [comment]
better solution #780

**Pull request closed without merging**
