### PR TITLE
A third small ECDSA fix

### PR DESCRIPTION
**Pull request by imachug**

### CODE REVIEW

**Comment by imachug** [comment]
@HelloZeroNet This is important, please merge this ASAP.

**Comment by imachug** [comment]
Thank you.

**Comment by HelloZeroNet** [comment]
Btw it's turned into an empty commit as I did the modification 3 hours ago: https://github.com/HelloZeroNet/ZeroNet/commit/dc23bfeb873d6bb165ad5a1607f0db73a5413568

**Comment by imachug** [comment]
xD GitHub is freaking me out, it sometimes shows that the fix is there and sometimes that it's not there

**Pull request merged**
