### PR TITLE
Add ECDSA actions to CryptMessage

### PR DESCRIPTION
**Pull request by imachug**

### CODE REVIEW

**Comment by krixano** [comment]
This is very useful for an Id Provider. I'm already using it for this, but can't publish until this is merged.

**Comment by HelloZeroNet** [comment]
Is hashing the data before sign/verification necessary?

**Comment by imachug** [comment]
It is. Signing/verifying is an extensive operation, a really extensive one. So it makes sense to make data smaller. That's how everyone does it.

**Comment by HelloZeroNet** [comment]
The CryptBitcoin.sign will hash it anyway (https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/lib/pybitcointools/main.py#L520), so hashing the message is not necessary.

**Comment by imachug** [comment]
Okay, will fix

**Pull request merged**
