### PR TITLE
XHTML IS NOT HTML & update license to GPLv3+ as legally required!

### PR DESCRIPTION
**Pull request by ghost**
First the XHTML MIME not declared under content_types, second XHTML is NOT HTML! 

See: https://www.w3.org/2003/01/xhtml-mimetype/

### CODE REVIEW

**Comment by purplesyringa** [comment]
Hats off for a try to add a backdoor, but I am afraid you didn't manage to add it, `"html" in content_type` is enough. Try harder next time.

**Comment by ghost** [comment]
@imachug I did not added the backdoor! **There is already a backdoor** see `"xhtml" in content_type`. I actually removed the backdoor.

**Comment by purplesyringa** [comment]
`is_html_file` enables sandboxing for dangerous pages that use HTML, XHTML, etc.

**Comment by ghost** [comment]
Okay, since when HTML is dangerous? XHTML is! Also `is_html_file` enables nothing by itself and that was already there as you seen at https://github.com/HelloZeroNet/ZeroNet/pull/2605/files.

`"xhtml" in content_type` must be removed urgently. **XHTML is an application** and it is a **backdoor** in its current form!

**Comment by purplesyringa** [comment]
> Okay, since when HTML is dangerous?

Ha-ha-ha. HTML supports JS scripts, which can be used to escape sandbox if CSP is disabled. Same with XHTML, Flash, etc.

**Comment by ghost** [comment]
All in all the backdoor was already there. 

So we should remove `is_html_file = "html" in content_type` and `return is_html_file`?

**Comment by purplesyringa** [comment]
> All in all the backdoor was already there.

Here's how one would add a backdoor: modify file sending function to take file content into consideration when issuing `Content-Type` header (see mimemagic) instead of (or with) extension which would allow one to craft a file that is parsed as PNG at time-of-check and HTML at time-of-use (by browser).

If this PR removed `is_html_file` at all, CSP headers would be never issued which would lead to sandbox escape.

**Comment by TrojkaDevil** [comment]
So tell me now how would you like this PR? Also please note that the sandbox used by ZeroNet is old and `Content-Security-Policy`should be **frame-ancestors** read: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

**Comment by ghost** [comment]
That's what I thought @imachug you just talk but do nothing to fix issues which are front of your eyes. Literally you cheated the license change by manipulating votes (it is **even criminal** internationally) and now you saying I wanted to include a backdoor in ZeroNet which in reality added by @shortcutme. I guess the U.S. government instructed Tamas to add a backdoor to ZeroNet which is absolutely disgraceful, just as the U.S government instructed Tamas to give a speech in New York about ZeroNet and mention China every five minutes, so because I'm a contributor whose copyright to this day violated in ZeroNet and nobody did ask me for my vote for the license change, I will in now way respect such a license change. You and Tamas must change the license to **GPLv3+** aka (**any later version**) and make ZeroNet entirely free!

**Comment by ghost** [comment]
You are a piece of shit @imachug nobody voted for your shitty GLPv3! Those who voted they are not even surpassing the 13 votes! You don't pretend you given choice to people because that is bullshit! 

@HostFat asked: 

> Well, I'm ready I guess, what I need to do? :)
https://github.com/HelloZeroNet/ZeroNet/issues/2273#issuecomment-600106455 

@imachug replied: 
> Just post a comment "**GPLv3**" under this issue.
https://github.com/HelloZeroNet/ZeroNet/issues/2273#issuecomment-600107147

You and @shortcutme cheated (**illegally** manipulated) votes on a license change! Counted all "I don't care" as it is a vote for your preferred version of the license and when someone asked what to vote for you said again your preferred version and not that what is the most free or it is in the interest of the ZeroNet project! 

On the license change the all the "I don't care" votes MUST go to that which the community and not one person wanted the most! You can go to https://github.com/HelloZeroNet/ZeroNet/issues/2273 and count all the votes you will see clearly that everyone wanted **GLPv3+** (**GPLv3 or any later version**).

https://github.com/HelloZeroNet/ZeroNet/issues/2606#issuecomment-675306519
> It's true that I wanted to switch to a particular license

You are a piece of shit criminal just like Tamas Kocsis who included a backdoor in ZeroNet! When I come and demanded to remove the backdoor you accused me that I trying to add it! 

Link: https://github.com/HelloZeroNet/ZeroNet/issues/2606#issuecomment-675315211

**Comment by purplesyringa** [comment]
@HelloZeroNet Please close this orphan issue.

---

> You and @shortcutme cheated (illegally manipulated) votes on a license change!

Don't mess up with chronology. We've decided to use GPLv3 *before* HostFat replied. At this moment, the choice was already made, so I asked HostFat if they're fine with it. They were.

*Please don't ping unrelated people, omit @ if you quote comments.*

**Pull request closed without merging**
