### PR TITLE
[Ready to be merged] Peer-to-peer applications

### PR DESCRIPTION
**Pull request by purplesyringa**
Implements a part of #1425.

## Current state

Practically finished, all features are tested.

Docs are ready (check wiki).

### CODE REVIEW

**Comment by imachug** [comment]
IRC test: [1FEL2HhvS48m8SsAPcuyo7irf7J9Ebx449.zip](https://github.com/HelloZeroNet/ZeroNet/files/2019238/1FEL2HhvS48m8SsAPcuyo7irf7J9Ebx449.zip)

Create a new site, upload those files, sign&publish and call others to open the site on their computers. Chat without limitations :)

**Comment by imachug** [comment]
@HelloZeroNet Need your advice.

Currently messages are broadcasted to any ~5 peers (or whatever the developer chooses). But those 5 peers may not have `P2P-messages` plugin, and they won't be able to broadcast the message. So we need to send the message only to those peers who have a specific plugin.

And here is the question: is it secure enough to add `getPluginList` FileRequest command? Or is it better to return *hashes* of plugin names? Or is it better to add `hasPlugin`? Or anything else?

**Comment by Thunder33345** [comment]
@imachug is it preferable to have a system ping, system pong
system ping and pong is meant for system(should only be accessed over plugin layer(maybe for more plugins that just connect via general peers unrelated to sites to use))

after you select your possible peers, you send systemping(with noreboradcast) to each peer(s), wait for their ping,
if you receive a pong back you add their ip/id/torid to a list of peers that have the plugin
if they didnt send a direct pong back after time out, it's safe to assume they didnt have the plugin, and add that to a cache for no plugin peers, then go back to step 1 of selecting other peers

ideally the peers will refresh every hour or some interval since things might change
also if you recieve a ping from a peer, you automatically set their IP to have the plugin

**Comment by imachug** [comment]
Some things not done yet:

- [x] peerBroadcast
- [ ] peerSend
- [ ] reply to peerSend

**Comment by imachug** [comment]
Updated [IRC](https://github.com/HelloZeroNet/ZeroNet/files/2020104/1FEL2HhvS48m8SsAPcuyo7irf7J9Ebx449.zip)

**Comment by krixano** [comment]
@Thunder33345 Here's the one that I have:
[P2P-messages.zip](https://github.com/HelloZeroNet/ZeroNet/files/2020119/P2P-messages.zip)

**Comment by imachug** [comment]
I hope this plugin will be embedded to ZeroNet via this PR, so soon you won't need `git clone`.

**Comment by krixano** [comment]
@imachug I've just added it as an option to my installer!

**Comment by imachug** [comment]
@krixano Thank you!

**Comment by imachug** [comment]
A better IRC site for tests: 
[1DdBX7wzwEaAEuEVQgYpMDhGCmXMXy9W6t.zip](https://github.com/HelloZeroNet/ZeroNet/files/2023567/1DdBX7wzwEaAEuEVQgYpMDhGCmXMXy9W6t.zip)

**Comment by Thunder33345** [comment]
also here's the address for handly sake http://127.0.0.1:43110/1DdBX7wzwEaAEuEVQgYpMDhGCmXMXy9W6t/
rehosting means no peers to chat to anyways
i guess might be time to get the new plugin version

**Comment by Thunder33345** [comment]
also i keep getting not connected to anyone using that address

**Comment by imachug** [comment]
@HelloZeroNet If you by any chance read this, please reply to https://github.com/HelloZeroNet/ZeroNet/pull/1430#issuecomment-390388350

**Comment by HelloZeroNet** [comment]
Probably the most efficient/easiest way would do it using javascript + cors/merger:
If the user has the plugin installed, then add a "p2p channel" site to the client and use that for broadcasting.

**Comment by imachug** [comment]
Sounds like a good solution without any need to change ZeroNet core. Thank you.

By the way, currently active protection (i.e. validation via JS) is done only if browser is open. However, this may not be the case. We (@Thunder33345, @krixano, @AnthyG and me) decided that we can make a new language, or a JavaScript interpreter which would run some file, e.g. `p2p.js` from site root when a new message is received. What do you think about this solution?

If you accept it, I would like to separate the plugin to another repository, because with the interpreter it's going to be large. You would either use submodules or subtrees or manually copy content from this another repository. You could either create it under @HelloZeroNet user and make me a collaborator (even if I make some security bug, it won't be added to this repo automatically, because submodules/subtrees aren't updated to the latest version by git automatically) or I can create a repo under @imachug and I'll add you as collaborator -- whatever you choose.

**Comment by Thunder33345** [comment]
>We (@Thunder33345, @krixano, @AnthyG and me) decided that we can make a new language, or a JavaScript interpreter which would run some file, e.g. p2p.js from site root when a new message is received. What do you think about this solution?

i think it should have a seperated plugin, with optional support for p2p plugin
since someone might just want to have something unrelated to p2p be ran at background
a only run on invoked will be better tho since it only exist when a packet is sent, unlike a file that exist until zeronet shutdown in something like nodejs style

**Comment by HelloZeroNet** [comment]
> we can make a new language, or a JavaScript interpreter which would run some file, e.g. p2p.js from site root when a new message is received. What do you think about this solution?

It would be useful in many cases, but I wanted to avoid it as it's hard to make it secure, so I think it's better keep it in a separate repository.

**Comment by imachug** [comment]
Will you create a repo for me under @HelloZeroNet and make a collaborator or do you let me create a repo under @imachug ?

**Comment by imachug** [comment]
I'm working on hub stuff. (i.e. read permissions)

**Comment by imachug** [comment]
Well, if we create our own language, like Solidity, it will be secure. I've created *a bunch* of languages (and they even worked *sigh*), so it might be a good idea.

**Comment by Thunder33345** [comment]
problem of creating a language is not begin flexible enough
if we adopt JS we already have the ecosystem we needed
if we make our new one, that means people have to reinvent things/libraries to get things started

for security sake, we can sandbox each background instance,
we can choose to not allow internet access, and block file system read+write

on the other hand, if we make our own, we dont need to deal with sandboxing, we can just make one that cant escape in the first place, but that means we are few steps behind everyone lacking in basic libraries that programmers rather have

**Comment by imachug** [comment]
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
> Will you create a repo for me under @HelloZeroNet and make a collaborator or do you let me create a repo under @imachug ?

Sure, but i'm not sure about the name. Maybe "PeerMessage" would be more accurate, than "P2P-Message".

**Comment by imachug** [comment]
PeerMessage sounds good -- renaming.

**Comment by imachug** [comment]
Renamed

**Comment by imachug** [comment]
By the way, that stuff running in background should be probably separated to another plugin. I've created repo for it: https://github.com/imachug/ZeroNet-Background

**Comment by imachug** [comment]
> I have added the repo for PeerMessage plugin: https://github.com/HelloZeroNet/Plugin-PeerMessage

Thank you for creating a repo! I'll push the stuff there and you can use `git submodule add` or something.

> As for the Background plugin name we should find a more exact name maybe BackgroundProcessing or DataProcessing?

Personally I'd use BackgroundProcessing.

**Comment by imachug** [comment]
I think I'll create some docs for this plugin (PeerMessage) - probably in GitHub Wiki.

And then I'll start implementing BackgroundProcessing - could you please create a repository for it as well, because I think it'll support several languages - and I think I even know how. And it'll include Wiki as well - so it's going to be too large to be included to ZeroNet main repository.

**Comment by imachug** [comment]
Most of the features of this plugin depend on BackgroundProcessing which I think I'll finish soon. So I think we shouldn't release it yet.

**Comment by DaniellMesquita** [comment]
> Well, if we create our own language, like Solidity, it will be secure. I've created a bunch of languages (and they even worked sigh), so it might be a good idea.

@imachug 
What do you think about creating ZeroNet's own cryptocurrency, that supports smart contracts in sidechains (like Lisk)?

@misses-robot
Also, how this plugin can be integrated with KopyKate to support live streamming of videos?
Or integrated with ThunderWave to support audio/video calls?

@AnthyG
Is good if you implement PeerMessage plugin to remove posting limits on ThunderWave.

**Comment by imachug** [comment]
@imachug I think you should ask @shortcutme, because he's the owner of ZeroNet.

**Comment by DaniellMesquita** [comment]
> I think you should ask @shortcutme, because he's the owner of ZeroNet.

@imachug 
Regarding the ZeroNet's cryptocurrency, I agree. But if he doesn't approves, we can't understand, because a own cryptocurrency can fund ZeroNet and its projects and bring ZN to investors/crypto enthusiasts. So, with approvation of Nofish or else, community should take a look at it.

But talking about live streamming features, I think you could answer it. Can your plugins achieve it?

**Comment by imachug** [comment]
Well, my plugins support plain-text now (and JSON), not binary data, but that should be enough for now.

**Comment by imachug** [comment]
@shortcutme @HelloZeroNet Finally, this plugin is ready to be merged!

**Comment by tangdou1** [comment]
Hope to see it!

**Comment by imachug** [comment]
@HelloZeroNet @shortcutme Any news on this? The plugin has been tested on various sites like [0Play Game Center](http://127.0.0.1:43110/1Ag6xidDHiPgWoDKhfSx4xFQr6WC3NqxZg) (games & chat), [/z/place](http://127.0.0.1:43110/1D6f2CvDRhPeEeBAcmqGt3X9z2CkLpmv2V/) and [KxoID](http://127.0.0.1:43110/1GTVetvjTEriCMzKzWSP9FahYoMPy6BG1P/?/), and it's not easy for most users to install plugins. This makes users angry, and they see that using ZeroNet isn't easy, so they stop using ZeroNet and tell everybody that it's some sh\*t no one should try to use, ZeroNet doesn't receive any donations and you don't have any money. 🤣

**Comment by DaniellMesquita** [comment]
@imachug
Look at the level you is, I never throught you could talk at this form, BUT CONGRATZ!
I think the same. ZeroNet needs more effort from us.
Lots of users registered ZeroMe in 2016 (really, lots), they didn't liked, left, talked to others "ZeroNet isn't all that people talked about, I didn't liked", and plans to never return to ZN.

**Comment by blurHY** [comment]
Why this is not merged

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
Thanks for the PR, I need more time to review it, but I think an easier way to install plugins would be better way to handle the third-party plugins as the developers would be able to update separately from zeronet client.

**Comment by trenta3** [comment]
@HelloZeroNet @imachug I think the plugin system should be handled much more carefully.

Imagine the following scenario (assuming the possibility of plugin updates from zeronet):
* Someone creates a good plugin for Private Sites (or another equally requested feature)
* Many people adopt it, and some even read the code and confirm it has no treat
* The plugin creator starts updating the code with small extra functionalities or bug fixes and at each modification he updates the plugins (each time asking the users for permission)
* At a later time, when everyone is just accepting updates to this plugin without thinking, he deploys malicious code that, starting from the next week (in order to have time to propagate to the whole net) does one of the following (at your choice):
   - Redirect all requests to zeronet to a blank page, and makes the program crash if some other action is allowed
   - Searches in the computer any cryptocurrencies wallet and logs user input
   - Deletes user' users.json and sites.json and/or encrypt them asking for money
   - ...

Moreover I think such a system has other downsides:
* Promotes duplication of efforts: there would be multiples copies of plugins with basically the same functionality and developed by a single author with no community support (just look at google chrome web store). This is bad since when the developer goes away, the plugin gets no security fixes and is abandoned (maybe because of non-existant documentation or commenting in source code).
* With the current plugin system ("patching" existing functions at beginning or at the end) the risks are for the plugins to interfere (installing two of them gives problems that when used by themselves they do not have) and to just crash when a Zeronet version is updated that does some noncompatible thing. One should then either not update (BAD) or wait for the plugin developer to notice that (if even) and have time to patch.
* Some plugins are just too important (such as this one) to only be optionally installable with user action. Many plugins offering additional functionality are just useless if they have to be opted in (e.g. RewriteRequest: noone would use such thing in his sites if there is the risk that some of the possible users cannot use the website, or Zeroname: many links have the domain name.bit).
* Zeronet **can't** let some random python code to execute "without control". Malicious code can do horrible things, and very few users have the time and knowledge to read source code and understand the risks.

Obviously some of these problems have solutions, but I'm just saying that such a thing requires careful planning (sandboxed environment / custom plugin language, more "modular" code patching, ...)

**Comment by imachug** [comment]
@HelloZeroNet Please don't think I'm rude. I appreciate your work and understand that it takes a lot of time and you have to do a lot outside the web. I just wanted to get a reply whether you're going to merge this later or whether I should keep it as a separate project, like I think we'll do with BackgroundProcessing.

**Comment by HelloZeroNet** [comment]
Adding an easy installable plugin store does have the possibility of serious security issue, so I think it's worth discussing if it's worth it or not.
On the other side I don't want to be responsible for merging a code that I'm not fully aware and reviewing new PR/plugins/changes can take lots of time. Sometime even more that writing it.

**Comment by tangdou1** [comment]
Developer should have more rights in developing plugin, so the idea of plugin store is really a good idea. Users should be responsible for their behavior to decide whether or not to add a plugin from the plugin store. Also most of them do not have much time to read the code of ZeroNet, but they must trust @HelloZeroNet if they want to use ZeroNet. Besides, a plugin store can improve community vitality of developing ZeroNet.

**Comment by blurHY** [comment]
I think we can use plugin as the backend of zite.That's handy

**Comment by trenta3** [comment]
> **HelloZeroNet**: [...] On the other side I don't want to be responsible for merging a code that I'm not fully aware and reviewing new PR/plugins/changes can take lots of time. Sometime even more than writing it.

@HelloZeroNet Concerning the review process, is there anything that can be done by committers to speed it up? Something about comments in the code, format of commit messages, programming style (e.g. function splitting), etc.?

If there is something that can be done, you could and should write precise requirements for code in Pull Requests in a visible place (in the main README or in a CONTRIBUTING.md). This helps both you, easing your review, and the pull request sender, who knows he is doing right and not creating too much burden on you.

> **tangdou1**: [...] Users should be responsible for their behavior to decide whether or not to add a plugin from the plugin store. Also most of them do not have much time or ability to read the code of ZeroNet, but they must trust @HelloZeroNet if they want to use ZeroNet. [...]

They are two very different stories: trusting HelloZeroNet (who has built almost the whole ZeroNet software) is very different from trusting a casual account that creates a plugin for ZeroNet, since you are basically trusting everyone that knows enough python to use decorators and to copy-paste from existing plugins. Even having a "reputation" system based on votes or comments adds nothing from the security side, since creating many zeroid accounts in very short time can be done. 
You would then have to trust HelloZeroNet in each case, since he is the one doing actual work.

As my last contribution in such discussion I'd like to add that using the current plugin infrastructure with the additional ability to add a plugin as a one-click action will be catastrophic in term of security as already explained, and there is currently no work-force to design and implement a better plugin system, so I think it just wont be done in the near future. IMHO one of the top priority should be to gain more widespread use and advertise ZeroNet as much as possible.

Please also note that the currently requested user actions for installing a plugin are: downloading the plugin code / folder in any way and putting it in a specific folder inside of the ZeroNet one. This already requires very basic abilities and little time.

**Comment by trenta3** [comment]
@krixano There was probably a misunderstanding: what I've said is "using the current plugin infrastructure with the additional ability to add a plugin as a one-click action will be catastrophic", so if we had a restricted API for plugins, it would be totally okay to have a one-click install.
The problem really arise when (with current plugin infrastructure) a one-click action could by design execute whatever code on your computer.

I'm particularly interested in the malicious code scan, do you have some references to working POCs or projects for python?

**Comment by blurHY** [comment]
Permission managing system is also needed for plugins

**Comment by imachug** [comment]
There is an idea. Not sure whether it works, but if it does, it could simplify installing plugins.

The idea is to have permissions for plugins. I mean, we can have `UiWebsocket` permission for changing UiWebsocket class, and `NOSANDBOX` permission for running without sandbox. Users can choose some plugins as safe (@HelloZeroNet's plugins well be marked as safe by default), which is the same as granting `NOSANDBOX` permission. 

The sandbox can be created from my BackgroundProcessing plugin. It turned out to work well for sites (as IP exchange service, backend for KxoID on @krixano's side, etc.) It is not an interpreter of Python, it only makes code that looks dangerous... not dangerous. So it's practically as fast as Vanilla Python.

Moreover, it means that @HelloZeroNet will only have to verify BackgroundProcessing, and other plugins will be executed via it.

**Comment by HelloZeroNet** [comment]
As far as I know there is no reliable sandbox for Python and writing a sandbox in Python itself is considered a bad idea: https://lwn.net/Articles/574215/

**Comment by krixano** [comment]
It's funny how one of the most used languages for plugins doesn't have proper sandbox support.

**Comment by HelloZeroNet** [comment]
Is there any language that has proper, supported and well tested sandboxing support? For example Visual Studio Code is written in js, but the plugins are not sandboxed either: https://github.com/Microsoft/vscode/issues/52116

**Comment by krixano** [comment]
Let me also clear up one more thing about what I was saying before:
* I do think that a restricted API and perhaps permission system, and perhaps (if achievable) sandboxing - would greatly increase security of plugins, as long as it's done right.
* However, I don't think any of that is needed before allowing a one-click install of a plugin
* This one-click install will be called by the zite, the zite giving a description and a zip file to the API command, where ZeroNet will *prompt* the user to install the plugin or not. If accepted, the ZeroNet *Client* will extract the folder in the zip, place it in the plugins directory, and refresh/reinitialize the plugins. There doesn't need to be any execution on the zite/plugin's side for the installation part.
* Security of plugins can be handled by a voting system, plugin review system, plugin scanner, flagging, etc. - which I think should all be implemented for plugin store *zites*, not the client.

**Comment by HelloZeroNet** [comment]
>Some languages, like JS, don't necessarily need sandboxing because the APIs etc. are already so restricted.

The sandboxing of JS is done by the browsers. For example in a VS Code plugin you can execute an external application with `child_process.spawnSync("notepad.exe")`. I think if we can't create a secure sandbox that prevent running external applications/creating sockets/etc., then the permission system makes no sense, as any plugin can easily ignore the rules.

**Comment by krixano** [comment]
@HelloZeroNet I see what you are getting at.

Additionally, I do think, as I was trying to get across above, that having code scanners, voting system, etc. would have a greater impact in a shorter amount of time.

**Comment by trenta3** [comment]
Just a little comment to that. 
It might be possible to build a python sandbox modifying a little [byterun](https://github.com/nedbat/byterun) (a [good article about it here](http://www.aosabook.org/en/500L/a-python-interpreter-written-in-python.html)).

The idea is simply: write a python interpreter inside python itself that allows only non-builtin functions to be called. Every time some interpreted pyton code calls an external module function, the interpreter could use `inspect.isbuiltin` and raise an exception if it is. If it is not, one should compile the function bytecode and execute that.

This could at least prevent accessing the filesystem, the network and other "external world" functions.

Finer restrictions on possible modifications of the ZeroNet classes I think would require a big amount of work.

**Comment by blurHY** [comment]
Consider to open an issue to talk about that

**Comment by trenta3** [comment]
@blurHY I should have done that before. Please use issue #1607 to discuss about plugin system and leave this thread only for things concerning the PR.

**Comment by imachug** [comment]
@HelloZeroNet What are your plans on this PR?

**Comment by filips123** [comment]
@HelloZeroNet @imachug This PR is now 1 year old. Can it be merged? Are there any important issues with it?

**Comment by imachug** [comment]
BTW the PeerMessage plugin repo has been updated, so this PR is outdated a bit. Let me update the submodule real fast

**Comment by imachug** [comment]
There, done.

**Comment by imachug** [comment]
I'm closing this PR as new changes should be only made on py3 branch, and there is a py3 version of this PR already.

**Pull request closed without merging**
