### PR TITLE
Search for any OpenSSL version in LD_LIBRARY_PATH

### LINKED ISSUE #2470: Openssl Lib Not Found Error.
```
if "LD_LIBRARY_PATH" in os.environ:
        lib_dir_paths = os.environ["LD_LIBRARY_PATH"].split(":")
        for path in lib_dir_paths:
            try:
                return [lib for lib in os.listdir(path) if "libcrypto.so.1.0" in lib [0]
```

Currently I was shipping `libcrypto.so.1.1` on ZeroNet Mobile, this results in openssl Lib not found error
@imachug @HelloZeroNet

### PR DESCRIPTION
**Pull request by purplesyringa**
Fixes #2470. Please check @canewsin.

### CODE REVIEW

**Comment by purplesyringa** [comment]
As a side note: sslcrypto supports all versions of OpenSSL, so even if this change didn't work before (with pyelliptic and such), it should work now.

**Comment by canewsin** [comment]
@imachug will find_library handle .so versioned libs ?

**Comment by purplesyringa** [comment]
Yeah, it's `in` operator so it will.

**Review by canewsin — APPROVED** [review]

**Comment by HelloZeroNet** [comment]
Thanks!

**Pull request merged**
