### PR TITLE
Added ZeroNet Logo to ReadMe

### PR DESCRIPTION
**Pull request by PSNAppz**

### CODE REVIEW

**Comment by anoadragon453** [comment]
Might be best to add it to the Chinese version of the README as well, no?

**Comment by PSNAppz** [comment]
@anoadragon453 The same one or Chinese one? I don't know chinese.

**Comment by ysc3839** [comment]
I think you should not upload to imgur.

**Comment by anoadragon453** [comment]
Preferably the name in English with the subtext in Chinese.

**Comment by MuxZeroNet** [comment]
ZeroNet logo improved by AceLewis
https://acelewis.com/post/zeronet-logo-improvements-and-svg

**Comment by Plasmmer** [comment]
You can upload the logo of AceLewis to the repo instead of using Imgur and PNG.

**Pull request closed without merging**
