### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/HelloZeroNet/ZeroNet/issues/2517

### CODE REVIEW

**Comment by ghost** [comment]
@filips123 was fast so he added a pre-release to requirements.txt. The stable version uploaded yesterday, see: https://pypi.org/project/gevent/1.5.0/#history

I also changed from 1.1.0 to 1.4.0 but be honest "gevent 1.5 runs on Python 2.7.9 and up, and Python 3.5, 3.6, 3.7 and 3.8" so this line going to be removed as well.

**Comment by ghost** [comment]
@filips123 opened fast another pull request when he seen my one: https://github.com/HelloZeroNet/ZeroNet/pull/2519 My pull request should be merged for obvious reasons.

**Comment by filips123** [comment]
I created this PR before I saw yours (although your was first). But yes, yours can be merged if you want.

**Comment by ghost** [comment]
@filips123 yes I want this to be merged, can you close your pull request? Thank you very much!

**Comment by filips123** [comment]
Gevent 1.5 does not support Python 3.4 but ZeroNet does.

**Comment by ghost** [comment]
@filips123 
> Gevent 1.5 does not support Python 3.4 but ZeroNet does.

https://pypi.org/project/gevent/1.5.0/#supprted-platforms well, maybe its is the time to drop support for 3.4. Don't you think @imachug? 

requirements.txt should only include gevent 1.5.0 because according to gevent maintainer older versions are not supported. 

> Users of older versions of Python 2 or Python 3 may install an older version of gevent. **Note that these versions are generally not supported.**

If someone running on older versions of python than that person should install the correct version of gevent which is **in most cases is version 1.5.0**. Since **Gevent 1.5.0 supports all version from 2.7.9 to up**, except 3.4 (:confused: strange) we should just drop support for that version.

**Comment by ultramassiveblackhole** [comment]
Ping-pong @HelloZeroNet

**Comment by filips123** [comment]
> well, maybe its is the time to drop support for 3.4. 

Time to drop 3.4 support was already few years ago...

> Since Gevent 1.5.0 supports all version from 2.7.9 to up, except 3.4

It support Python 2.7+, except 3.0, 3.1, 3.2 and 3.3. Basically Python 2.7 and 3.5+.

**Comment by ghost** [comment]
@filips123 
> It support Python 2.7+, except 3.0, 3.1, 3.2 and 3.3. Basically Python 2.7 and 3.5+.

It support Python 2.7+, except 3.0, 3.1, 3.2, 3.3 **and 3.4**. Basically Python 2.7 and 3.5+. :+1: 

So what now? You @filips123 run 3.8 and I guess @imachug 3.7 which is 3.5+, I think most people have at least python version 3.5. 

Again, older versions of gevent are not supported! Why would someone who has Python 3.7 want to install gevent 1.1.0? Makes no sense. 

I recommend to merge this and if anyone have Python 3.4 probably we will see it when opening an issue about it and than we can link this conversation. I don't think that anyone from here running Python 3.4, probably not even 2.7. My guess is that in 2020 at least Python version 3.6 is installed for most.

**Comment by purplesyringa** [comment]
> https://pypi.org/project/gevent/1.5.0/#supported-platforms well, maybe its is the time to drop support for 3.4. Don't you think @imachug?

I don't think so. Python 3.4 is still the latest available version on some devices. We've dropped Python 2 support just around a year ago, it's not the right time to drop 3.4 yet.

**Comment by ghost** [comment]
> > https://pypi.org/project/gevent/1.5.0/#supported-platforms well, maybe its is the time to drop support for 3.4. Don't you think @imachug?
> 
> I don't think so. Python 3.4 is still the latest available version on some devices. We've dropped Python 2 support just around a year ago, it's not the right time to drop 3.4 yet.

https://github.com/HelloZeroNet/ZeroNet/pull/2518#issuecomment-612415864 
Show me @imachug  just one device which uses Python 3.4. :thinking: What device you talk about some robot on Mars? 

Termux on Android for that matter has Python version 3.8.2. 
@styromaniac what version of Python you have?

**Comment by purplesyringa** [comment]
Okay, let me say what I meant another way. Currently, ZeroNet doesn't use any Python 3.5-specific functions or something, so there's no reason to stop Python 3.4 support when the only Python 3.4-related detail is a single line in `requirements.txt`.

**Comment by ghost** [comment]
So,

gevent=1.2.2 ; python_version=="3.3"
gevent=1.3.7 ; python_version=="3.4"
gevent=1.4.0 ; python_version=="3.4.3"
gevent=1.5.0

@filips123

@imachug this is not just one line...

**Comment by purplesyringa** [comment]
> this is not just one line

It used to be a single line before your PR. Anyway, can't we just request `>=1.1.0` for Python 3.4 and below and `>=1.5.0` for Python 3.5 and above?

**Comment by ghost** [comment]
> > this is not just one line
> 
> It used to be a single line before your PR. Anyway, can't we just request `>=1.1.0` for Python 3.4 and below and `>=1.5.0` for Python 3.5 and above?

@imachug 
No because https://pypi.org/project/gevent/1.5.0/#older-versions-of-python clearly shows that 1.1.0 is not good for Python version 3.4.3 for example. We can also separate requirements.txt because again, gevent 1.5.0 supports python version 2.7.9 and 3.5+ but not versions 3.0-3.4.3. 

gevent

in the other hand **1.1.0 is just about 4 years old** release of gevent: https://pypi.org/project/gevent/1.5.0/#history

**Comment by purplesyringa** [comment]
How is it "not good"? It's `>=`, not `=`.

**Comment by ghost** [comment]
> How is it "not good"? It's `>=`, not `=`.

@imachug 
It is just stupid to use a 4 year old version of gevent when there is newer and very specifically stating what version of gevent supports which version of python. You can't just use 1.1.0 for Python version 3.4.3 because it is not supported! 

It is not better to have the correct version of gevent for the correct version of python? Pip would install version 1.1.0 for python 2.7.9 when in reality gevent 1.5.0 supports that! 

It is better to say the correct version even if its takes more lines in requirements.txt

**Comment by ghost** [comment]
@jamadden can you comment on this? :thinking:

**Comment by purplesyringa** [comment]
> It is not better to have the correct version of gevent for the correct version of python? Pip would install version 1.1.0 for python 2.7.9 when in reality gevent 1.5.0 supports that!

Do you know what `>=` means? It installs *any* version greater than or equal to the given one. If a compatible version is already installed, it doesn't do anything; if it's not, it downloads the latest compatible version which is exactly what we want.

**Comment by ghost** [comment]
> > It is not better to have the correct version of gevent for the correct version of python? Pip would install version 1.1.0 for python 2.7.9 when in reality gevent 1.5.0 supports that!
> 
> Do you know what `>=` means? It installs _any_ version greater than or equal to the given one. If a compatible version is already installed, it doesn't do anything; if it's not, it downloads the latest compatible version which is exactly what we want. 

> gevent 1.3 runs on Python 2.7 and Python 3. Releases 3.4, 3.5 and 3.6 of Python 3 are supported. (Users of older versions of Python 2 need to install gevent 1.0.x (2.5), 1.1.x (2.6) or 1.2.x (<=2.7.8); gevent 1.2 can be installed on Python 3.3.) 

Something like this would be better @imachug :

gevent==1.2.2; python_version<=2.7.8
gevent==1.4.0; python_version>=3.3;<3.5
gevent=1.5.0

or 

gevent>=1.2.2
gevent==1.5.0; python_version=2.7.9;>3.5 :thinking: 

@filips123 any comment? 


**gevent>=1.2.2
gevent==1.5.0 ; python_version == '2.7.9' or python_version >= '3.5'** :+1:

**Comment by purplesyringa** [comment]
> `python_version == '2.7.9'`

We don't support Python 2 anymore so this part is useless.

**Comment by ultramassiveblackhole** [comment]
> > `python_version == '2.7.9'`
> 
> We don't support Python 2 anymore so this part is useless.

gevent>=1.2.2
gevent==1.5.0 ; python_version >= "3.5" 

is good @imachug?

**Comment by ghost** [comment]
@imachug in Travis all failed above Python 3.5 :confused:

**Comment by purplesyringa** [comment]
I see

**Comment by ghost** [comment]
What the hell? :confused:

**Comment by ghost** [comment]
gevent>=1.4.0 :+1: Problem solved, 1.4.0 also pretty fresh, at least is not 4 years old and @imachug just reminded me that ZeroNet not supporting python 2.x anymore so it would be irresponsible to have 1.1.0 as minimum version for gevent. All checks have passed with  gevent>=1.4.0 :hugs: :partying_face:

**Comment by HelloZeroNet** [comment]
gevent 1.4.0 not supported on Python 3.8 and as far as I know there is no incompatibility issues with earlier versions of gevent, so no reason to require 1.4.0.

I have changed to >=1.5.0 on python 3.8: https://github.com/HelloZeroNet/ZeroNet/commit/f3a839f422afd50f5bf8f17d83a8807571bc1dfe

**Pull request closed without merging**
