### PR TITLE
potential fix for #2323

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks, it would be great if we could reproduce the problem and make sure gevent.lock.RLock works for different threads.

and probably it would be better to use
```
try:
    from gevent.lock import RLock
except:
    from gevent.coros import RLock
```

as gevent.coros was only used up until gevent 1.2.0 (2016-12-23)

**Comment by ghost** [comment]
> Thanks, it would be great if we could reproduce the problem and make sure gevent.lock.RLock works for different threads.
> 
> and probably it would be better to use
> 
> ```
> try:
>     from gevent.lock import RLock
> except:
>     from gevent.coros import RLock
> ```
> 
> as gevent.coros was only used up until gevent 1.2.0 (2016-12-23)

No problem, changed the import statements. 
As for reproducing the problem, I'm not sure... The issue only gives a vague description of what the problem is.

**Comment by HelloZeroNet** [comment]
I was able to reproduce a similar problem:
```
sqlite3.OperationalError: cannot start a transaction within a transaction
2019-11-23T11:40:59Z <Greenlet at 0x350c8c8: threadedExecute(['INSERT INTO test (key, value) VALUES (?, ?)', (0)> failed with OperationalError
```

Unfortunately looks like RLock does not work between threads:

```

  File "C:\Python3\lib\site-packages\gevent\lock.py", line 223, in acquire
    rc = self._block.acquire(blocking)
  File "src\gevent\_semaphore.py", line 100, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_semaphore.py", line 128, in gevent.__semaphore.Semaphore.acquire
  File "src\gevent\_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src\gevent\_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
greenlet.error: cannot switch to a different thread
```

But it work this way:

```py
    global is_executing
    while is_executing:
        time.sleep(0.01)
    is_executing = True

    try:
        res = db.execute(*query)
    finally:
        is_executing = False
    return res
```

it's not the most elegant solution and some unnecessary sleep could happen, but it has minimal overhead under normal conditions and expect that this this will happen rarely.

my full test script:
```py
import time
import gevent
import gevent.monkey
import gevent.threadpool
import sqlite3
import shutil
gevent.monkey.patch_all(thread=False, threading=False)

def watcher():
    print("Watcher started")
    while 1:
        s = time.time()
        time.sleep(0.1)
        if time.time() - s > 0.15:
            print("- Block:", time.time() - s)
gevent.spawn(watcher)

db = sqlite3.connect("db.db", isolation_level="DEFERRED", check_same_thread=False)
db.row_factory = sqlite3.Row
try:
    db.execute("DROP TABLE test")
except Exception as err:
    pass
db.execute('PRAGMA journal_mode=WAL')
db.execute("CREATE TABLE test (key INTEGER, value TEXT)")

pool_db = gevent.threadpool.ThreadPool(10)

from gevent.lock import RLock
import gevent.thread

is_executing = False
num_blocked = 0
lock = RLock()
def execute(*query):
    global is_executing, num_blocked
    while is_executing:
        num_blocked += 1
        time.sleep(0.01)
    is_executing = True

    try:
        res = db.execute(*query)
    finally:
        is_executing = False
    return res

def threadedExecute(query):
    res = pool_db.spawn(execute, *query).get()
    return [query, res.fetchall()]

s = time.time()
threads = []
for i in range(1000):
    query = ["INSERT INTO test (key, value) VALUES (?, ?)", (i, "data %s" % i)]
    t = gevent.spawn(threadedExecute, query)
    threads.append(t)

gevent.joinall(threads)
print("Insert executed in %.3fs" % (time.time() - s))
print("Blocked:", num_blocked)

threads = []
for i in range(1000):
    query = ["SELECT * FROM test WHERE test.value LIKE 'data %s%%' OR test.value = ? LIMIT 5" % i, ["data %s" % i]]
    t = gevent.spawn(threadedExecute, query)
    threads.append(t)

gevent.joinall(threads)
print("Select executed in %.3fs" % (time.time() - s))
print("Blocked:", num_blocked)

for thread in threads:
    query, res = thread.value
    assert len(res), "No result for: %s" % query
    assert res[0]["value"].startswith(query[1][0]), "%s not starts with %s" % (res[0]["value"], query[1])

```

**Comment by HelloZeroNet** [comment]
Update: `from gevent._threading import Lock` looks compatible with threading, so replacing RLock with that should work

**Comment by ghost** [comment]
So replace reentrant locks with Locks and see if that works?

**Pull request merged**
