### PR TITLE
Decodes IGD response to utf-8; Makes function arguments immutable;

### PR DESCRIPTION
**Pull request by sirMackk**
This is a very likely fix for #725. Didn't get a confirmation yet, but I wanted to have this PR ready now.

I made the ol' mistake where I thought that urlopen().read() returns a text string, but it's a byte string, and `xml.minidom.parseString` expects a text string. Easily solved by decoding the byte string into a text string.

The other small change is to make the default function arguments that are _mutable_ lists into immutable tuples. Using a mutable object as a default function argument is an invitation to all sorts of pain.

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
are the `,` necessary at the `('TCP', 'UDP',)` ?

```
>>> ("TCP", "UDP") == ("TCP", "UDP",)
True
```

**Comment by sirMackk** [comment]
Absolutely not! It's just a style thing - in my opinion, the `,` at the end instantly identifies the parenthesis as tuple. But if you don't like it, I'd be more than happy to get rid of the `,`'s :).

**Comment by HelloZeroNet** [comment]
For me it's looks like an unfinished function call, so i would prefer without it. (I know its necessary for tuples with only one element)

**Comment by sirMackk** [comment]
Thanks for the feedback, I never thought of it that way. I removed the commas and rebased my branch.

**Pull request merged**
