### PR TITLE
Support web notifications

### PR DESCRIPTION
**Pull request by imachug**

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Looking good, but I'm not sure if PushNotification permission is necessary, as the notifications only going to work when the browser tab is opened, because lack of the serviceworker service

**Comment by imachug** [comment]
I am sure this is required. If you allow notifications for 127.0.0.1, then all the zites would be able to send notifications. It's better to have explict confirmation. Compare it to Clearnet: you have to allow noifications for each site.

**Comment by HelloZeroNet** [comment]
I think on clearnet the notification confirmation is required, because if you accept it, then the sites also able to send you notification if you are not on the page. Bot for us it's not the case, because there are no service workers.

**Comment by imachug** [comment]
Okay, done.

**Pull request merged**
