### PR TITLE
Switch from gevent-websocket to gevent-ws

### PR DESCRIPTION
**Pull request by purplesyringa**
Replacing the slow library with my own fast MIT-licensed library. I'm not sure if this will break bundled clients though, you might want to copy the source (https://github.com/imachug/gevent-ws) to the `lib` directory.

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
It will broke the bundles/updates from web interface, so supporting both is necessary. (looks easy to do)
Also: The run_application modification is necessary for error handling.

**Comment by purplesyringa** [comment]
K, will fix.

**Comment by purplesyringa** [comment]
I've restored `run_application` (refactored it a bit) and also added `gevent_ws` to `lib`. I think that supporting both libraries is not necessary because `gevent_ws` is way faster.

**Comment by purplesyringa** [comment]
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
Thanks, I will test it and merge later today. Do you have numbers how much faster is it?

**Comment by purplesyringa** [comment]
> Do you have numbers how much faster is it?

IIRC `gevent-websocket` can handle around 50 Mbps and my library can handle around 750 Mbps (just streaming zeroes).

**Comment by HelloZeroNet** [comment]
Thanks, looking great!

**Pull request merged**
