### PR TITLE
[WIP] Porting TorManager to Stem

### PR DESCRIPTION
**Pull request by MuxZeroNet**
Use Stem if we have it

### CODE REVIEW

**Comment by MuxZeroNet** [comment]
```bash
python zeronet.py --tor always --tor_proxy 127.0.0.1:9150 --tor_controller 127.0.0.1:9151 --disable_udp
```
```
TorManager Authenticate using Stem... 127.0.0.1:9151
TorManager Tor stem connect error: SOCKS5Error: 0x01: General SOCKS server failure in TorManager.py line 213 > control.py line 998 > socket.py line 372 > socket.py line 243 > socket.py line 398 > socks.py line 681 > socks.py line 383 > socks.py line 458
TorManager self-bundled Tor fallback: Tor proxy port 127.0.0.1:9150 check error: No connection
```

**Comment by HelloZeroNet** [comment]
Thanks, but I think it would be better as separate plugin, so you can avoid lots of ifs and does not makes the core source code more complicated. (it's easy check DonationMessage for example)

you can add to plugin's __init__.py like this:
```
try:
    import from stem.control import Controller 
    import StemPlugin
except:
   pass
```

and then easily override connect/addOnion/etc methods of TorController in StemPlugin.py

**Comment by MuxZeroNet** [comment]
@HelloZeroNet Stem tends to route Tor Control Port information through the Tor Socks5 proxy. Any workaround for this?

**Comment by HelloZeroNet** [comment]
Probably this is what needs to be modified: https://github.com/HelloZeroNet/ZeroNet/blob/master/src/util/SocksProxy.py#L6

**Comment by MuxZeroNet** [comment]
How do I write the first lines of the plugin?
```python
@PluginManager.registerTo("TorManager")
class TorManagerPlugin(object):
```

**Pull request closed without merging**
