### PR TITLE
Create Portuguese (Portugal) translation

### PR DESCRIPTION
**Pull request by megfault**

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks, please use "pt.json" and also translate other files:
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Translate/languages/hu.json
https://github.com/HelloZeroNet/ZeroHello/blob/master/languages/hu.json
https://github.com/HelloZeroNet/ZeroMe/blob/master/languages/hu.json
https://github.com/HelloZeroNet/ZeroTalk/blob/master/languages/hu.json

**Comment by megfault** [comment]
Usually Portuguese from Portugal is named pt-pt, as opposed to pt-br from Brazil. Shall I stick to pt.json and use pt-br.json for Brazilian Portuguese? Or just br.json (which looks kinda wrong to me, but if it fits your naming scheme better...)?

**Comment by HelloZeroNet** [comment]
there is no convencion for that, possible solutions: `pt-br.json`, `pt-BR.json`, `pt_BR.json` all used and looks fine for me

**Comment by Plasmmer** [comment]
@megfault & @HelloZeroNet, some news?

**Comment by megfault** [comment]
@Plasmmer Hey, sorry!! I somehow got busy with Real Life(TM). I will try to submit a translation for European Portuguese soon. I see there is a Brazilian one already so I will just base mine on it.

**Pull request closed without merging**
