### PR TITLE
License GPLv3+

### PR DESCRIPTION
**Pull request by ghost**
This commit fixing the license issue: https://github.com/HelloZeroNet/ZeroNet/issues/2273

### CODE REVIEW

**Comment by purplesyringa** [comment]
@HelloZeroNet Close this orphaned PR please.

**Comment by Crypto-Anarchist** [comment]
Kiss my ass please.

**Comment by russianagent** [comment]
@HelloZeroNet @imachug We should merge this based on the recent voting which by the way the most active issue in this repository well over 500 comments. 

@filips123 are you okay with this?

**Comment by purplesyringa** [comment]
@HelloZeroNet

**Pull request closed without merging**
