### PR TITLE
BUHH

### PR DESCRIPTION
**Pull request by ghost**
:angry:

### CODE REVIEW

**Comment by hacktivist** [comment]
You just don't wanted to merge my PR because you and some kids are so fucking ignorant that it was better to break my pull request but you are also a retard because the security hole is front of your eyes. In the big rush you forgot copy that one from my PR.

**Comment by HelloZeroNet** [comment]
Please open a new issue with the details if you found any security problem.

**Comment by ghost** [comment]
I'm gonna take a wild guess and say that he's talking about line 281 in his pr @HelloZeroNet

**Comment by ghost** [comment]
Screenshot from 2019-10-28 11-43-09

**Comment by HelloZeroNet** [comment]
The no-referrer header does not fixes the linked issue.
To avoid tabnabbing we would need to add `noopener` rel to the links, but as far as I know there is no way to do it by http headers.

**Comment by ghost** [comment]
@HelloZeroNet https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#tabnabbing
Screenshot from 2019-10-28 11-56-58

Also, we have the `wrapperOpenWindow` zeroframe cmd that we need to do this for.

**Comment by HelloZeroNet** [comment]
The wrapperOpenWindow already work like this:
https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Ui/media/Wrapper.coffee#L235

**Comment by ghost** [comment]
Ok, I didn't know that. Good!

**Comment by ghost** [comment]
> The wrapperOpenWindow already work like this:
> https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Ui/media/Wrapper.coffee#L235

Sending the header is better!

**Pull request closed without merging**
