### PR TITLE
Upgrade License to GNU General Public License v3.0 or later

### PR DESCRIPTION
**Pull request by antifa**
In this pull request: 

- Deleted incompatible and terminated GPLv2 license.
- Created a new **GPL-3.0-or-later** `LICENSE`.
- Created a new file `COPYING` which referenced by `LICENSE`.

`COPYING` includes the full **GNU General Public License v3.0**. 
`LICENSE` should be updated on a later time with _GPL linking exceptions_ as described in [section 7 of GPLv3+](https://www.gnu.org/licenses/gpl-3.0-standalone.html#section7).

### CODE REVIEW

**Comment by 0x6a73** [comment]
This pull request cannot be accepted unless every single commiter accepts it. If you're a commiter and you agree for an upgrade to GPLv3, please relicense your code.

**Comment by antifa** [comment]
Hello @0x6a73, 

I kindly ask you to not to spam this pull request because it is extremely important. There are various discussions already where your comments are welcome.

**Comment by 0x6a73** [comment]
Fuck off, you're the one creating three different issues and spamming them up with your nonsense. At least try to use arguments here.

**Comment by 0x6a73** [comment]
Links to issue pages with arguments for or against this change:
https://github.com/HelloZeroNet/ZeroNet/issues/2268

Still, you're legally obliged by the law of the USA, UE, Switzerland and many more countries to personally ask commiters for permission to relicense your work. Otherwise enjoy getting sued if even one of them declines.

**Comment by antifa** [comment]
I asked you not to spam this pull request! Which part you did not understand? 

The **permission you talk about you need not because of the upgrade to GPLv3+**, you need permission if you want to get rid of most of the source code which is incompatible with GPLv2. Basically destroying other peoples work. Ask permission for that! 

Please read this: https://github.com/HelloZeroNet/ZeroNet/issues/2268#issuecomment-549087242 and stop spamming this pull request. Thank you!

**Comment by 0x6a73** [comment]
1. Learn the definition of "spam"
2. You're not the boss here.
3. An upgrade from a proprietary license to GPLv3+ isn't legal without permission of software's authors. If you think it is, go ahead and do so with Linux.

**Comment by antifa** [comment]
Never in this life an open source software become proprietary if it is released under such a license. 

While the license is automatically terminated in this ZeroNet repository is worth to note that my repository is compliant with all licenses and as someone who contributed to ZeroNet until my repository exist, either on GitHub or in my computer the software can't become proprietary ever!

**Comment by 0x6a73** [comment]
You said that the software didn't meet GPLv2's requirements, rendering its license "non-existent". That means that all rights and requirements stated in the GPLv2 are revoked and don't apply anymore. Do you know what is a piece of software without a license? That's right, proprietary. Without clear rights on what you can and cannot do, its author can sue you for illegal use of his software. That's the reason why we actually have licenses - not to protect the author, but to protect its users.

Your repository has relicensed the software without previous authorization, therefore breaking the law. Now, any commiter is eligible to ask for a DMCA takedown of your repo. I mean, I've already reported it, but I'm quite sure that DMCA takedowns take a lot less time.

**Comment by gthedevel** [comment]
@antifa 
How would ZeroNet profit from an upgrade to GPLv3?

**Comment by antifa** [comment]
Just not Viktor Orban himself? :rofl: @0x6a73 I know that is you! **Stop spamming the pull request!**

**Comment by antifa** [comment]
@xfq Can you take a look at this? There are various open issues about the license of ZeroNet!

**Comment by blazercrypter** [comment]
[https://boards.4channel.org/g/thread/73404780](https://boards.4channel.org/g/thread/73404780)

**Comment by gthedevel** [comment]
> Just not Viktor Orban himself?  @0x6a73 I know that is you! **Stop spamming the pull request!**

Nope, I'm a random 4chan poster.
By the way I realize what you want to do: you think that by changing the license to one that allows patents, you can then claim that what you contributed is yours and take control over the whole project
Well guess what buddy, that won't happen so you might as well just stop harassing the people here. Take your schizo meds, buddy.

**Comment by antifa** [comment]
@gthedevel This is not a forum! I understand that you are excited but please understand that you can't just sign up and post spam to a pull request! I answering you legitimate question below.

The license change is needed so that ZeroNet can continue to advance while complying with all software licenses what the source code includes. With the license change nobody, and I repeat nobody can take over the project, but if the license upgrade is not going to be done urgently than ZeroNet is effectively a dead end. :skull_and_crossbones: 

Regarding the patent use, you must know that everyone is able to apply for patent according to GPLv3 but this does not equal to the patent you see from big corporations. No exclusive right is granted to patent ZeroNet itself. Let's say 4chan want to apply for a patent where indicates that uses ZeroNet to distribute posts. 4chan will get the patent but will not own ZeroNet ever! This is a protection mechanism of GPLv3 which is protecting the users even from the creator of ZeroNet. The creator @shortcutme can't claim patent and restrict the use of ZeroNet in any ways, he will be also forbidden to incorporate mechanisms which renders the program unusable if someone changes the source code! 

GPLv3 is not only more free than any previous GPL licenses but also it is compatible with many others, while GPLv2 is not! GPLv2 is nearly 30 years old. Since ZeroNet for years used a license which is violated various other licenses there is nothing else can be done to save ZeroNet except the license upgrade in the main repository. 

Even if the ZeroNet main repository is not upgraded to GPLv3 (which is required) than everyone who has knowledge about this license issue must upgrade the license in they repositories! 

Please ask your questions here: https://github.com/HelloZeroNet/ZeroNet/issues/2269 here: https://github.com/HelloZeroNet/ZeroNet/issues/2268 or here: https://github.com/HelloZeroNet/ZeroNet/issues/2265

**Comment by antifa** [comment]
@xfq if you are around please check this out!

**Comment by 0x6a73** [comment]
@antifa Actually, this IS a forum, meant for discussion of issues and new features of Zeronet. I see that you really can't google up that single article and check out what a PR and an issue means?

We've already talked about the patent thing in the issue and why the so called "patent protections" in GPLv3 isn't quite okay, because of the ability to take over a project and etc.

Also, seriously? You're accusing me of creating multiple accounts for "spamming" a PR while that's the exact thing you did(removeddit/4chan links above)? Disgusting.

**Comment by 0x6a73** [comment]
Also, just to clarify since your Reddit post got deleted:
https://www.removeddit.com/r/github/comments/dqi53i/what_happens_if_a_repository_violated_three/
As a commiter you do not hold copyright to the entire software, just to that small piece of code you commited.
BTW, ban evasion is a reason to get you banned from Github altogether. I've already contacted the support to take care of that.

**Comment by antifa** [comment]
I going to report your account to GitHub if you not stop spamming the pull request! I asked you kindly not to do it and you invited here people from 4chan to do! You also opened various pull request in my repository and you posting only insult because you are a Polish neo-Nazi trash. You love Hungary and other Nazi countries? Than go there and fuck yourself. I hope we will go to war and I will have a chance to give you a bullet in the head.

**Comment by 0x6a73** [comment]
@HelloZeroNet Since situation here is slowly getting out of hand, could you help to resolve this?

@antifa Go ahead. I already did the same thing. Unlike you, the Github Support Team knows the meaning of spam. Also, what do you mean that I invited people from 4chan here? They've found the thread by themselves. Moreover, everyone has a right to express their view on this change, no matter what their political opinions are.

(BTW, 4chan's /g/ isn't neccesarily equivalent to /pol/)

**Comment by 0x6a73** [comment]
Also, saying that "I hope I'll have a chance to give you a bullet in the head" is not only a big violation of Github's terms, but also illegal and may be used against you in court. I'm posting a screenshot just in case you delete your posts again.
image

**Comment by xddxd** [comment]
ssou
@antifa TRIGGER ALERT

**Pull request closed without merging**
