### PR TITLE
Added super call for resolveDomain function

### PR DESCRIPTION
**Pull request by rllola**
Related to #2128

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
The problem is there is no resolveDomain function in the SiteManager, so it will drop exception on non-existent domains.

I think it's better to override the get() and need() function instead in the other plugin and not the resolveDomain one.

Other solution would be adding isDomain(address) and resolveDomain(address) to SiteManager.py that is always return False by default and name resolving plugins could override these functions. (we have to rename resolveDomain to resolveBitDomain in Zeroname plugin)

**Comment by rllola** [comment]
The other plugin has a `get()` and `need()` function and it is failing.

> Other solution would be adding isDomain(address) and resolveDomain(address) to SiteManager.py that is always return False by default and name resolving plugins could override these functions. (we have to rename resolveDomain to resolveBitDomain in Zeroname plugin)

I can try that but isn't it going to fail when others call `resolveDomain` ?

**Comment by rllola** [comment]
What I understand is happening is that `actioinSiteMedia` from `ZeroName` plugin is called it resolve the domain name (with `resolveDomain`) :
https://github.com/HelloZeroNet/ZeroNet/blob/py3/plugins/Zeroname/UiRequestPlugin.py#L15-L22

Then it is call `actioinSiteMedia` from `TranslateSite` which is called and then the `ENS` plugin. So ENS plugin hasn't resolve the domain name and `TranslateSite` is left with `example.eth` instead of a proper address.

**Comment by rllola** [comment]
Now that I think about it ordering the plugins might sound like a better idea but it would leave too much freedom and therefore might implies lots of support...

Otherwise is there any way to decouple resolving the domain from the `actionSiteMedia` call... ?

**Comment by rllola** [comment]
Closing this as modification has been added in https://github.com/HelloZeroNet/ZeroNet/commit/2bdd07360854bb7920c52efc28913211e4d47ab1

**Pull request closed without merging**
