### PR TITLE
Ui: actionConsole: remove unused main variable

### PR DESCRIPTION
**Pull request by radfish**
Looks unused, but please correct me if there's something subtle here.

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
It's just a shortcut. The /Console spawns an interactive console to the current context, so pre-defining the main makes it easier to access the main module context.

**Comment by radfish** [comment]
Ok. I don't get an interactive prompt at /Console (just a dump), so I didn't realize this. Thanks.

**Comment by HelloZeroNet** [comment]
It requires to install the pip package "werkzeug" to receive the interactive console

**Comment by radfish** [comment]
On Sun, Apr 07, 2019 at 03:02:37PM -0700, ZeroNet wrote:
> It requires to install the pip package "werkzeug" to receive the interactive console

Thanks. Hm. installed Werkzeug==0.15.2 but same: just a dump at
/Console. Perhaps worth investigating. Maybe some more packages needed?
(This is on the current upstream py3 branch.)

**Pull request closed without merging**
